<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/protocol/v1/message.proto

namespace GPBMetadata\Temporal\Api\Protocol\V1;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAD\x03\x0A&temporal/api/protocol/v1/message.proto\x12\x18temporal.api.protocol.v1\"\xCA\x01\x0A\x07Message\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x120\x0A\x14protocol_instance_id\x18\x02 \x01(\x09R\x12protocolInstanceId\x12\x1B\x0A\x08event_id\x18\x03 \x01(\x03H\x00R\x07eventId\x12%\x0A\x0Dcommand_index\x18\x04 \x01(\x03H\x00R\x0CcommandIndex\x12(\x0A\x04body\x18\x05 \x01(\x0B2\x14.google.protobuf.AnyR\x04bodyB\x0F\x0A\x0Dsequencing_idB\x93\x01\x0A\x1Bio.temporal.api.protocol.v1B\x0CMessageProtoP\x01Z'go.temporal.io/api/protocol/v1;protocol\xAA\x02\x1ATemporalio.Api.Protocol.V1\xEA\x02\x1DTemporalio::Api::Protocol::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

