<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websockets/v2/request.proto

namespace RoadRunner\Websockets\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>websockets.v2.WebsocketRequest</code>
 */
class WebsocketRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .websockets.v2.WebsocketMessage messages = 1 [json_name = "messages"];</code>
     */
    private $messages;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Websockets\DTO\V2\WebsocketMessage[] $messages
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Websockets\DTO\V2\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .websockets.v2.WebsocketMessage messages = 1 [json_name = "messages"];</code>
     * @return RepeatedField<\RoadRunner\Websockets\DTO\V2\WebsocketMessage>
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>repeated .websockets.v2.WebsocketMessage messages = 1 [json_name = "messages"];</code>
     * @param \RoadRunner\Websockets\DTO\V2\WebsocketMessage[] $var
     * @return $this
     */
    public function setMessages(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Websockets\DTO\V2\WebsocketMessage::class);
        $this->messages = $arr;

        return $this;
    }

}

