<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/command/v1/message.proto

namespace Temporal\Api\Command\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.command.v1.StartChildWorkflowExecutionCommandAttributes</code>
 */
class StartChildWorkflowExecutionCommandAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     */
    protected $workflow_id = '';
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowType workflow_type = 3 [json_name = "workflowType"];</code>
     */
    protected $workflow_type = null;
    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 4 [json_name = "taskQueue"];</code>
     */
    protected $task_queue = null;
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads input = 5 [json_name = "input"];</code>
     */
    protected $input = null;
    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 6 [json_name = "workflowExecutionTimeout"];</code>
     */
    protected $workflow_execution_timeout = null;
    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 7 [json_name = "workflowRunTimeout"];</code>
     */
    protected $workflow_run_timeout = null;
    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 8 [json_name = "workflowTaskTimeout"];</code>
     */
    protected $workflow_task_timeout = null;
    /**
     * Default: PARENT_CLOSE_POLICY_TERMINATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ParentClosePolicy parent_close_policy = 9 [json_name = "parentClosePolicy"];</code>
     */
    protected $parent_close_policy = 0;
    /**
     * Generated from protobuf field <code>string control = 10 [json_name = "control"];</code>
     */
    protected $control = '';
    /**
     * Default: WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.WorkflowIdReusePolicy workflow_id_reuse_policy = 11 [json_name = "workflowIdReusePolicy"];</code>
     */
    protected $workflow_id_reuse_policy = 0;
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 12 [json_name = "retryPolicy"];</code>
     */
    protected $retry_policy = null;
    /**
     * Establish a cron schedule for the child workflow.
     *
     * Generated from protobuf field <code>string cron_schedule = 13 [json_name = "cronSchedule"];</code>
     */
    protected $cron_schedule = '';
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Header header = 14 [json_name = "header"];</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 15 [json_name = "memo"];</code>
     */
    protected $memo = null;
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 16 [json_name = "searchAttributes"];</code>
     */
    protected $search_attributes = null;
    /**
     * If this is set, the child workflow inherits the Build ID of the parent. Otherwise, the assignment
     * rules of the child's Task Queue will be used to independently assign a Build ID to it.
     * Deprecated. Only considered for versioning v0.2.
     *
     * Generated from protobuf field <code>bool inherit_build_id = 17 [json_name = "inheritBuildId", deprecated = true];</code>
     * @deprecated
     */
    protected $inherit_build_id = false;
    /**
     * Priority metadata. If this message is not present, or any fields are not
     * present, they inherit the values from the workflow.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 18 [json_name = "priority"];</code>
     */
    protected $priority = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $workflow_id
     *     @type \Temporal\Api\Common\V1\WorkflowType $workflow_type
     *     @type \Temporal\Api\Taskqueue\V1\TaskQueue $task_queue
     *     @type \Temporal\Api\Common\V1\Payloads $input
     *     @type \Google\Protobuf\Duration $workflow_execution_timeout
     *           Total workflow execution timeout including retries and continue as new.
     *     @type \Google\Protobuf\Duration $workflow_run_timeout
     *           Timeout of a single workflow run.
     *     @type \Google\Protobuf\Duration $workflow_task_timeout
     *           Timeout of a single workflow task.
     *     @type int $parent_close_policy
     *           Default: PARENT_CLOSE_POLICY_TERMINATE.
     *     @type string $control
     *     @type int $workflow_id_reuse_policy
     *           Default: WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE.
     *     @type \Temporal\Api\Common\V1\RetryPolicy $retry_policy
     *     @type string $cron_schedule
     *           Establish a cron schedule for the child workflow.
     *     @type \Temporal\Api\Common\V1\Header $header
     *     @type \Temporal\Api\Common\V1\Memo $memo
     *     @type \Temporal\Api\Common\V1\SearchAttributes $search_attributes
     *     @type bool $inherit_build_id
     *           If this is set, the child workflow inherits the Build ID of the parent. Otherwise, the assignment
     *           rules of the child's Task Queue will be used to independently assign a Build ID to it.
     *           Deprecated. Only considered for versioning v0.2.
     *     @type \Temporal\Api\Common\V1\Priority $priority
     *           Priority metadata. If this message is not present, or any fields are not
     *           present, they inherit the values from the workflow.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Command\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return string
     */
    public function getWorkflowId()
    {
        return $this->workflow_id;
    }

    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->workflow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowType workflow_type = 3 [json_name = "workflowType"];</code>
     * @return \Temporal\Api\Common\V1\WorkflowType|null
     */
    public function getWorkflowType()
    {
        return $this->workflow_type;
    }

    public function hasWorkflowType()
    {
        return isset($this->workflow_type);
    }

    public function clearWorkflowType()
    {
        unset($this->workflow_type);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowType workflow_type = 3 [json_name = "workflowType"];</code>
     * @param \Temporal\Api\Common\V1\WorkflowType $var
     * @return $this
     */
    public function setWorkflowType(\Temporal\Api\Common\V1\WorkflowType|null $var)
    {
        $this->workflow_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 4 [json_name = "taskQueue"];</code>
     * @return \Temporal\Api\Taskqueue\V1\TaskQueue|null
     */
    public function getTaskQueue()
    {
        return $this->task_queue;
    }

    public function hasTaskQueue()
    {
        return isset($this->task_queue);
    }

    public function clearTaskQueue()
    {
        unset($this->task_queue);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 4 [json_name = "taskQueue"];</code>
     * @param \Temporal\Api\Taskqueue\V1\TaskQueue $var
     * @return $this
     */
    public function setTaskQueue(\Temporal\Api\Taskqueue\V1\TaskQueue|null $var)
    {
        $this->task_queue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads input = 5 [json_name = "input"];</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getInput()
    {
        return $this->input;
    }

    public function hasInput()
    {
        return isset($this->input);
    }

    public function clearInput()
    {
        unset($this->input);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads input = 5 [json_name = "input"];</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setInput(\Temporal\Api\Common\V1\Payloads|null $var)
    {
        $this->input = $var;

        return $this;
    }

    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 6 [json_name = "workflowExecutionTimeout"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowExecutionTimeout()
    {
        return $this->workflow_execution_timeout;
    }

    public function hasWorkflowExecutionTimeout()
    {
        return isset($this->workflow_execution_timeout);
    }

    public function clearWorkflowExecutionTimeout()
    {
        unset($this->workflow_execution_timeout);
    }

    /**
     * Total workflow execution timeout including retries and continue as new.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_execution_timeout = 6 [json_name = "workflowExecutionTimeout"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowExecutionTimeout(\Google\Protobuf\Duration|null $var)
    {
        $this->workflow_execution_timeout = $var;

        return $this;
    }

    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 7 [json_name = "workflowRunTimeout"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowRunTimeout()
    {
        return $this->workflow_run_timeout;
    }

    public function hasWorkflowRunTimeout()
    {
        return isset($this->workflow_run_timeout);
    }

    public function clearWorkflowRunTimeout()
    {
        unset($this->workflow_run_timeout);
    }

    /**
     * Timeout of a single workflow run.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_run_timeout = 7 [json_name = "workflowRunTimeout"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowRunTimeout(\Google\Protobuf\Duration|null $var)
    {
        $this->workflow_run_timeout = $var;

        return $this;
    }

    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 8 [json_name = "workflowTaskTimeout"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getWorkflowTaskTimeout()
    {
        return $this->workflow_task_timeout;
    }

    public function hasWorkflowTaskTimeout()
    {
        return isset($this->workflow_task_timeout);
    }

    public function clearWorkflowTaskTimeout()
    {
        unset($this->workflow_task_timeout);
    }

    /**
     * Timeout of a single workflow task.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration workflow_task_timeout = 8 [json_name = "workflowTaskTimeout"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setWorkflowTaskTimeout(\Google\Protobuf\Duration|null $var)
    {
        $this->workflow_task_timeout = $var;

        return $this;
    }

    /**
     * Default: PARENT_CLOSE_POLICY_TERMINATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ParentClosePolicy parent_close_policy = 9 [json_name = "parentClosePolicy"];</code>
     * @return int one of the values in {@see \Temporal\Api\Enums\V1\ParentClosePolicy}
     */
    public function getParentClosePolicy()
    {
        return $this->parent_close_policy;
    }

    /**
     * Default: PARENT_CLOSE_POLICY_TERMINATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.ParentClosePolicy parent_close_policy = 9 [json_name = "parentClosePolicy"];</code>
     * @param int $var one of the values in {@see \Temporal\Api\Enums\V1\ParentClosePolicy}
     * @return $this
     */
    public function setParentClosePolicy(int $var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\ParentClosePolicy::class);
        $this->parent_close_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string control = 10 [json_name = "control"];</code>
     * @return string
     */
    public function getControl()
    {
        return $this->control;
    }

    /**
     * Generated from protobuf field <code>string control = 10 [json_name = "control"];</code>
     * @param string $var
     * @return $this
     */
    public function setControl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->control = $var;

        return $this;
    }

    /**
     * Default: WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.WorkflowIdReusePolicy workflow_id_reuse_policy = 11 [json_name = "workflowIdReusePolicy"];</code>
     * @return int one of the values in {@see \Temporal\Api\Enums\V1\WorkflowIdReusePolicy}
     */
    public function getWorkflowIdReusePolicy()
    {
        return $this->workflow_id_reuse_policy;
    }

    /**
     * Default: WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.WorkflowIdReusePolicy workflow_id_reuse_policy = 11 [json_name = "workflowIdReusePolicy"];</code>
     * @param int $var one of the values in {@see \Temporal\Api\Enums\V1\WorkflowIdReusePolicy}
     * @return $this
     */
    public function setWorkflowIdReusePolicy(int $var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\WorkflowIdReusePolicy::class);
        $this->workflow_id_reuse_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 12 [json_name = "retryPolicy"];</code>
     * @return \Temporal\Api\Common\V1\RetryPolicy|null
     */
    public function getRetryPolicy()
    {
        return $this->retry_policy;
    }

    public function hasRetryPolicy()
    {
        return isset($this->retry_policy);
    }

    public function clearRetryPolicy()
    {
        unset($this->retry_policy);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.RetryPolicy retry_policy = 12 [json_name = "retryPolicy"];</code>
     * @param \Temporal\Api\Common\V1\RetryPolicy $var
     * @return $this
     */
    public function setRetryPolicy(\Temporal\Api\Common\V1\RetryPolicy|null $var)
    {
        $this->retry_policy = $var;

        return $this;
    }

    /**
     * Establish a cron schedule for the child workflow.
     *
     * Generated from protobuf field <code>string cron_schedule = 13 [json_name = "cronSchedule"];</code>
     * @return string
     */
    public function getCronSchedule()
    {
        return $this->cron_schedule;
    }

    /**
     * Establish a cron schedule for the child workflow.
     *
     * Generated from protobuf field <code>string cron_schedule = 13 [json_name = "cronSchedule"];</code>
     * @param string $var
     * @return $this
     */
    public function setCronSchedule(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cron_schedule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Header header = 14 [json_name = "header"];</code>
     * @return \Temporal\Api\Common\V1\Header|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Header header = 14 [json_name = "header"];</code>
     * @param \Temporal\Api\Common\V1\Header $var
     * @return $this
     */
    public function setHeader(\Temporal\Api\Common\V1\Header|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 15 [json_name = "memo"];</code>
     * @return \Temporal\Api\Common\V1\Memo|null
     */
    public function getMemo()
    {
        return $this->memo;
    }

    public function hasMemo()
    {
        return isset($this->memo);
    }

    public function clearMemo()
    {
        unset($this->memo);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Memo memo = 15 [json_name = "memo"];</code>
     * @param \Temporal\Api\Common\V1\Memo $var
     * @return $this
     */
    public function setMemo(\Temporal\Api\Common\V1\Memo|null $var)
    {
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 16 [json_name = "searchAttributes"];</code>
     * @return \Temporal\Api\Common\V1\SearchAttributes|null
     */
    public function getSearchAttributes()
    {
        return $this->search_attributes;
    }

    public function hasSearchAttributes()
    {
        return isset($this->search_attributes);
    }

    public function clearSearchAttributes()
    {
        unset($this->search_attributes);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.SearchAttributes search_attributes = 16 [json_name = "searchAttributes"];</code>
     * @param \Temporal\Api\Common\V1\SearchAttributes $var
     * @return $this
     */
    public function setSearchAttributes(\Temporal\Api\Common\V1\SearchAttributes|null $var)
    {
        $this->search_attributes = $var;

        return $this;
    }

    /**
     * If this is set, the child workflow inherits the Build ID of the parent. Otherwise, the assignment
     * rules of the child's Task Queue will be used to independently assign a Build ID to it.
     * Deprecated. Only considered for versioning v0.2.
     *
     * Generated from protobuf field <code>bool inherit_build_id = 17 [json_name = "inheritBuildId", deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getInheritBuildId()
    {
        if ($this->inherit_build_id !== false) {
            @trigger_error('inherit_build_id is deprecated.', E_USER_DEPRECATED);
        }
        return $this->inherit_build_id;
    }

    /**
     * If this is set, the child workflow inherits the Build ID of the parent. Otherwise, the assignment
     * rules of the child's Task Queue will be used to independently assign a Build ID to it.
     * Deprecated. Only considered for versioning v0.2.
     *
     * Generated from protobuf field <code>bool inherit_build_id = 17 [json_name = "inheritBuildId", deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setInheritBuildId(bool $var)
    {
        @trigger_error('inherit_build_id is deprecated.', E_USER_DEPRECATED);
        $this->inherit_build_id = $var;

        return $this;
    }

    /**
     * Priority metadata. If this message is not present, or any fields are not
     * present, they inherit the values from the workflow.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 18 [json_name = "priority"];</code>
     * @return \Temporal\Api\Common\V1\Priority|null
     */
    public function getPriority()
    {
        return $this->priority;
    }

    public function hasPriority()
    {
        return isset($this->priority);
    }

    public function clearPriority()
    {
        unset($this->priority);
    }

    /**
     * Priority metadata. If this message is not present, or any fields are not
     * present, they inherit the values from the workflow.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Priority priority = 18 [json_name = "priority"];</code>
     * @param \Temporal\Api\Common\V1\Priority $var
     * @return $this
     */
    public function setPriority(\Temporal\Api\Common\V1\Priority|null $var)
    {
        $this->priority = $var;

        return $this;
    }

}

