<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Used for manual deletion of Versions. User can delete a Version only when all the
 * following conditions are met:
 *  - It is not the Current or Ramping Version of its Deployment.
 *  - It has no active pollers (none of the task queues in the Version have pollers)
 *  - It is not draining (see WorkerDeploymentVersionInfo.drainage_info). This condition
 *    can be skipped by passing `skip-drainage=true`.
 *
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.DeleteWorkerDeploymentVersionRequest</code>
 */
class DeleteWorkerDeploymentVersionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Deprecated. Use `deployment_version`.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version", deprecated = true];</code>
     * @deprecated
     */
    protected $version = '';
    /**
     * Required.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion deployment_version = 5 [json_name = "deploymentVersion"];</code>
     */
    protected $deployment_version = null;
    /**
     * Pass to force deletion even if the Version is draining. In this case the open pinned
     * workflows will be stuck until manually moved to another version by UpdateWorkflowExecutionOptions.
     *
     * Generated from protobuf field <code>bool skip_drainage = 3 [json_name = "skipDrainage"];</code>
     */
    protected $skip_drainage = false;
    /**
     * Optional. The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     */
    protected $identity = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $version
     *           Deprecated. Use `deployment_version`.
     *     @type \Temporal\Api\Deployment\V1\WorkerDeploymentVersion $deployment_version
     *           Required.
     *     @type bool $skip_drainage
     *           Pass to force deletion even if the Version is draining. In this case the open pinned
     *           workflows will be stuck until manually moved to another version by UpdateWorkflowExecutionOptions.
     *     @type string $identity
     *           Optional. The identity of the client who initiated this request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Deprecated. Use `deployment_version`.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version", deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getVersion()
    {
        if ($this->version !== '') {
            @trigger_error('version is deprecated.', E_USER_DEPRECATED);
        }
        return $this->version;
    }

    /**
     * Deprecated. Use `deployment_version`.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version", deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setVersion(string $var)
    {
        @trigger_error('version is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Required.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion deployment_version = 5 [json_name = "deploymentVersion"];</code>
     * @return \Temporal\Api\Deployment\V1\WorkerDeploymentVersion|null
     */
    public function getDeploymentVersion()
    {
        return $this->deployment_version;
    }

    public function hasDeploymentVersion()
    {
        return isset($this->deployment_version);
    }

    public function clearDeploymentVersion()
    {
        unset($this->deployment_version);
    }

    /**
     * Required.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion deployment_version = 5 [json_name = "deploymentVersion"];</code>
     * @param \Temporal\Api\Deployment\V1\WorkerDeploymentVersion $var
     * @return $this
     */
    public function setDeploymentVersion(\Temporal\Api\Deployment\V1\WorkerDeploymentVersion|null $var)
    {
        $this->deployment_version = $var;

        return $this;
    }

    /**
     * Pass to force deletion even if the Version is draining. In this case the open pinned
     * workflows will be stuck until manually moved to another version by UpdateWorkflowExecutionOptions.
     *
     * Generated from protobuf field <code>bool skip_drainage = 3 [json_name = "skipDrainage"];</code>
     * @return bool
     */
    public function getSkipDrainage()
    {
        return $this->skip_drainage;
    }

    /**
     * Pass to force deletion even if the Version is draining. In this case the open pinned
     * workflows will be stuck until manually moved to another version by UpdateWorkflowExecutionOptions.
     *
     * Generated from protobuf field <code>bool skip_drainage = 3 [json_name = "skipDrainage"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipDrainage(bool $var)
    {
        $this->skip_drainage = $var;

        return $this;
    }

    /**
     * Optional. The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Optional. The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

}

