<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * [cleanup-wv-pre-release] Pre-release deployment APIs, clean up later
 *
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.ListDeploymentsRequest</code>
 */
class ListDeploymentsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;
    /**
     * Generated from protobuf field <code>bytes next_page_token = 3 [json_name = "nextPageToken"];</code>
     */
    protected $next_page_token = '';
    /**
     * Optional. Use to filter based on exact series name match.
     *
     * Generated from protobuf field <code>string series_name = 4 [json_name = "seriesName"];</code>
     */
    protected $series_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type int $page_size
     *     @type string $next_page_token
     *     @type string $series_name
     *           Optional. Use to filter based on exact series name match.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 3 [json_name = "nextPageToken"];</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 3 [json_name = "nextPageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * Optional. Use to filter based on exact series name match.
     *
     * Generated from protobuf field <code>string series_name = 4 [json_name = "seriesName"];</code>
     * @return string
     */
    public function getSeriesName()
    {
        return $this->series_name;
    }

    /**
     * Optional. Use to filter based on exact series name match.
     *
     * Generated from protobuf field <code>string series_name = 4 [json_name = "seriesName"];</code>
     * @param string $var
     * @return $this
     */
    public function setSeriesName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->series_name = $var;

        return $this;
    }

}

