<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.PollWorkflowTaskQueueRequest</code>
 */
class PollWorkflowTaskQueueRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 2 [json_name = "taskQueue"];</code>
     */
    protected $task_queue = null;
    /**
     * The identity of the worker/client who is polling this task queue
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * Deprecated. Use deployment_options instead.
     * Each worker process should provide an ID unique to the specific set of code it is running
     * "checksum" in this field name isn't very accurate, it should be though of as an id.
     *
     * Generated from protobuf field <code>string binary_checksum = 4 [json_name = "binaryChecksum", deprecated = true];</code>
     * @deprecated
     */
    protected $binary_checksum = '';
    /**
     * Deprecated. Use deployment_options instead.
     * Information about this worker's build identifier and if it is choosing to use the versioning
     * feature. See the `WorkerVersionCapabilities` docstring for more.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionCapabilities worker_version_capabilities = 5 [json_name = "workerVersionCapabilities", deprecated = true];</code>
     * @deprecated
     */
    protected $worker_version_capabilities = null;
    /**
     * Worker deployment options that user has set in the worker.
     * Experimental. Worker Deployments are experimental and might significantly change in the future.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 6 [json_name = "deploymentOptions"];</code>
     */
    protected $deployment_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type \Temporal\Api\Taskqueue\V1\TaskQueue $task_queue
     *     @type string $identity
     *           The identity of the worker/client who is polling this task queue
     *     @type string $binary_checksum
     *           Deprecated. Use deployment_options instead.
     *           Each worker process should provide an ID unique to the specific set of code it is running
     *           "checksum" in this field name isn't very accurate, it should be though of as an id.
     *     @type \Temporal\Api\Common\V1\WorkerVersionCapabilities $worker_version_capabilities
     *           Deprecated. Use deployment_options instead.
     *           Information about this worker's build identifier and if it is choosing to use the versioning
     *           feature. See the `WorkerVersionCapabilities` docstring for more.
     *     @type \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $deployment_options
     *           Worker deployment options that user has set in the worker.
     *           Experimental. Worker Deployments are experimental and might significantly change in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 2 [json_name = "taskQueue"];</code>
     * @return \Temporal\Api\Taskqueue\V1\TaskQueue|null
     */
    public function getTaskQueue()
    {
        return $this->task_queue;
    }

    public function hasTaskQueue()
    {
        return isset($this->task_queue);
    }

    public function clearTaskQueue()
    {
        unset($this->task_queue);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.TaskQueue task_queue = 2 [json_name = "taskQueue"];</code>
     * @param \Temporal\Api\Taskqueue\V1\TaskQueue $var
     * @return $this
     */
    public function setTaskQueue(\Temporal\Api\Taskqueue\V1\TaskQueue|null $var)
    {
        $this->task_queue = $var;

        return $this;
    }

    /**
     * The identity of the worker/client who is polling this task queue
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the worker/client who is polling this task queue
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Deprecated. Use deployment_options instead.
     * Each worker process should provide an ID unique to the specific set of code it is running
     * "checksum" in this field name isn't very accurate, it should be though of as an id.
     *
     * Generated from protobuf field <code>string binary_checksum = 4 [json_name = "binaryChecksum", deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getBinaryChecksum()
    {
        if ($this->binary_checksum !== '') {
            @trigger_error('binary_checksum is deprecated.', E_USER_DEPRECATED);
        }
        return $this->binary_checksum;
    }

    /**
     * Deprecated. Use deployment_options instead.
     * Each worker process should provide an ID unique to the specific set of code it is running
     * "checksum" in this field name isn't very accurate, it should be though of as an id.
     *
     * Generated from protobuf field <code>string binary_checksum = 4 [json_name = "binaryChecksum", deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setBinaryChecksum(string $var)
    {
        @trigger_error('binary_checksum is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->binary_checksum = $var;

        return $this;
    }

    /**
     * Deprecated. Use deployment_options instead.
     * Information about this worker's build identifier and if it is choosing to use the versioning
     * feature. See the `WorkerVersionCapabilities` docstring for more.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionCapabilities worker_version_capabilities = 5 [json_name = "workerVersionCapabilities", deprecated = true];</code>
     * @return \Temporal\Api\Common\V1\WorkerVersionCapabilities|null
     * @deprecated
     */
    public function getWorkerVersionCapabilities()
    {
        if (isset($this->worker_version_capabilities)) {
            @trigger_error('worker_version_capabilities is deprecated.', E_USER_DEPRECATED);
        }
        return $this->worker_version_capabilities;
    }

    public function hasWorkerVersionCapabilities()
    {
        if (isset($this->worker_version_capabilities)) {
            @trigger_error('worker_version_capabilities is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->worker_version_capabilities);
    }

    public function clearWorkerVersionCapabilities()
    {
        @trigger_error('worker_version_capabilities is deprecated.', E_USER_DEPRECATED);
        unset($this->worker_version_capabilities);
    }

    /**
     * Deprecated. Use deployment_options instead.
     * Information about this worker's build identifier and if it is choosing to use the versioning
     * feature. See the `WorkerVersionCapabilities` docstring for more.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionCapabilities worker_version_capabilities = 5 [json_name = "workerVersionCapabilities", deprecated = true];</code>
     * @param \Temporal\Api\Common\V1\WorkerVersionCapabilities $var
     * @return $this
     * @deprecated
     */
    public function setWorkerVersionCapabilities(\Temporal\Api\Common\V1\WorkerVersionCapabilities|null $var)
    {
        @trigger_error('worker_version_capabilities is deprecated.', E_USER_DEPRECATED);
        $this->worker_version_capabilities = $var;

        return $this;
    }

    /**
     * Worker deployment options that user has set in the worker.
     * Experimental. Worker Deployments are experimental and might significantly change in the future.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 6 [json_name = "deploymentOptions"];</code>
     * @return \Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null
     */
    public function getDeploymentOptions()
    {
        return $this->deployment_options;
    }

    public function hasDeploymentOptions()
    {
        return isset($this->deployment_options);
    }

    public function clearDeploymentOptions()
    {
        unset($this->deployment_options);
    }

    /**
     * Worker deployment options that user has set in the worker.
     * Experimental. Worker Deployments are experimental and might significantly change in the future.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 6 [json_name = "deploymentOptions"];</code>
     * @param \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $var
     * @return $this
     */
    public function setDeploymentOptions(\Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null $var)
    {
        $this->deployment_options = $var;

        return $this;
    }

}

