<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.RecordActivityTaskHeartbeatRequest</code>
 */
class RecordActivityTaskHeartbeatRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     */
    protected $task_token = '';
    /**
     * Arbitrary data, of which the most recent call is kept, to store for this activity
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads details = 2 [json_name = "details"];</code>
     */
    protected $details = null;
    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     */
    protected $namespace = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_token
     *           The task token as received in `PollActivityTaskQueueResponse`
     *     @type \Temporal\Api\Common\V1\Payloads $details
     *           Arbitrary data, of which the most recent call is kept, to store for this activity
     *     @type string $identity
     *           The identity of the worker/client
     *     @type string $namespace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->task_token = $var;

        return $this;
    }

    /**
     * Arbitrary data, of which the most recent call is kept, to store for this activity
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads details = 2 [json_name = "details"];</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Arbitrary data, of which the most recent call is kept, to store for this activity
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads details = 2 [json_name = "details"];</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setDetails(\Temporal\Api\Common\V1\Payloads|null $var)
    {
        $this->details = $var;

        return $this;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

}

