<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.RespondActivityTaskCompletedByIdRequest</code>
 */
class RespondActivityTaskCompletedByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Namespace of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     */
    protected $workflow_id = '';
    /**
     * Run Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     */
    protected $run_id = '';
    /**
     * Id of the activity to complete
     *
     * Generated from protobuf field <code>string activity_id = 4 [json_name = "activityId"];</code>
     */
    protected $activity_id = '';
    /**
     * The serialized result of activity execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads result = 5 [json_name = "result"];</code>
     */
    protected $result = null;
    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 6 [json_name = "identity"];</code>
     */
    protected $identity = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *           Namespace of the workflow which scheduled this activity
     *     @type string $workflow_id
     *           Id of the workflow which scheduled this activity
     *     @type string $run_id
     *           Run Id of the workflow which scheduled this activity
     *     @type string $activity_id
     *           Id of the activity to complete
     *     @type \Temporal\Api\Common\V1\Payloads $result
     *           The serialized result of activity execution
     *     @type string $identity
     *           The identity of the worker/client
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Namespace of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Namespace of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return string
     */
    public function getWorkflowId()
    {
        return $this->workflow_id;
    }

    /**
     * Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->workflow_id = $var;

        return $this;
    }

    /**
     * Run Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     * @return string
     */
    public function getRunId()
    {
        return $this->run_id;
    }

    /**
     * Run Id of the workflow which scheduled this activity
     *
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRunId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->run_id = $var;

        return $this;
    }

    /**
     * Id of the activity to complete
     *
     * Generated from protobuf field <code>string activity_id = 4 [json_name = "activityId"];</code>
     * @return string
     */
    public function getActivityId()
    {
        return $this->activity_id;
    }

    /**
     * Id of the activity to complete
     *
     * Generated from protobuf field <code>string activity_id = 4 [json_name = "activityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setActivityId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->activity_id = $var;

        return $this;
    }

    /**
     * The serialized result of activity execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads result = 5 [json_name = "result"];</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * The serialized result of activity execution
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads result = 5 [json_name = "result"];</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setResult(\Temporal\Api\Common\V1\Payloads|null $var)
    {
        $this->result = $var;

        return $this;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 6 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 6 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

}

