<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.RespondNexusTaskCompletedRequest</code>
 */
class RespondNexusTaskCompletedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 2 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * A unique identifier for this task as received via a poll response.
     *
     * Generated from protobuf field <code>bytes task_token = 3 [json_name = "taskToken"];</code>
     */
    protected $task_token = '';
    /**
     * Embedded response to be translated into a frontend response.
     *
     * Generated from protobuf field <code>.temporal.api.nexus.v1.Response response = 4 [json_name = "response"];</code>
     */
    protected $response = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $identity
     *           The identity of the client who initiated this request.
     *     @type string $task_token
     *           A unique identifier for this task as received via a poll response.
     *     @type \Temporal\Api\Nexus\V1\Response $response
     *           Embedded response to be translated into a frontend response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 2 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the client who initiated this request.
     *
     * Generated from protobuf field <code>string identity = 2 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * A unique identifier for this task as received via a poll response.
     *
     * Generated from protobuf field <code>bytes task_token = 3 [json_name = "taskToken"];</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * A unique identifier for this task as received via a poll response.
     *
     * Generated from protobuf field <code>bytes task_token = 3 [json_name = "taskToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->task_token = $var;

        return $this;
    }

    /**
     * Embedded response to be translated into a frontend response.
     *
     * Generated from protobuf field <code>.temporal.api.nexus.v1.Response response = 4 [json_name = "response"];</code>
     * @return \Temporal\Api\Nexus\V1\Response|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Embedded response to be translated into a frontend response.
     *
     * Generated from protobuf field <code>.temporal.api.nexus.v1.Response response = 4 [json_name = "response"];</code>
     * @param \Temporal\Api\Nexus\V1\Response $var
     * @return $this
     */
    public function setResponse(\Temporal\Api\Nexus\V1\Response|null $var)
    {
        $this->response = $var;

        return $this;
    }

}

