<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.RespondActivityTaskFailedRequest</code>
 */
class RespondActivityTaskFailedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     */
    protected $task_token = '';
    /**
     * Detailed failure information
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2 [json_name = "failure"];</code>
     */
    protected $failure = null;
    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Additional details to be stored as last activity heartbeat
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_heartbeat_details = 5 [json_name = "lastHeartbeatDetails"];</code>
     */
    protected $last_heartbeat_details = null;
    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @deprecated
     */
    protected $worker_version = null;
    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 7 [json_name = "deployment", deprecated = true];</code>
     * @deprecated
     */
    protected $deployment = null;
    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 8 [json_name = "deploymentOptions"];</code>
     */
    protected $deployment_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_token
     *           The task token as received in `PollActivityTaskQueueResponse`
     *     @type \Temporal\Api\Failure\V1\Failure $failure
     *           Detailed failure information
     *     @type string $identity
     *           The identity of the worker/client
     *     @type string $namespace
     *     @type \Temporal\Api\Common\V1\Payloads $last_heartbeat_details
     *           Additional details to be stored as last activity heartbeat
     *     @type \Temporal\Api\Common\V1\WorkerVersionStamp $worker_version
     *           Version info of the worker who processed this task. This message's `build_id` field should
     *           always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     *           field to true. See message docstrings for more.
     *           Deprecated. Use `deployment_options` instead.
     *     @type \Temporal\Api\Deployment\V1\Deployment $deployment
     *           Deployment info of the worker that completed this task. Must be present if user has set
     *           `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     *           Deprecated. Replaced with `deployment_options`.
     *     @type \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $deployment_options
     *           Worker deployment options that user has set in the worker.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * The task token as received in `PollActivityTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->task_token = $var;

        return $this;
    }

    /**
     * Detailed failure information
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2 [json_name = "failure"];</code>
     * @return \Temporal\Api\Failure\V1\Failure|null
     */
    public function getFailure()
    {
        return $this->failure;
    }

    public function hasFailure()
    {
        return isset($this->failure);
    }

    public function clearFailure()
    {
        unset($this->failure);
    }

    /**
     * Detailed failure information
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 2 [json_name = "failure"];</code>
     * @param \Temporal\Api\Failure\V1\Failure $var
     * @return $this
     */
    public function setFailure(\Temporal\Api\Failure\V1\Failure|null $var)
    {
        $this->failure = $var;

        return $this;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 4 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Additional details to be stored as last activity heartbeat
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_heartbeat_details = 5 [json_name = "lastHeartbeatDetails"];</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getLastHeartbeatDetails()
    {
        return $this->last_heartbeat_details;
    }

    public function hasLastHeartbeatDetails()
    {
        return isset($this->last_heartbeat_details);
    }

    public function clearLastHeartbeatDetails()
    {
        unset($this->last_heartbeat_details);
    }

    /**
     * Additional details to be stored as last activity heartbeat
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads last_heartbeat_details = 5 [json_name = "lastHeartbeatDetails"];</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setLastHeartbeatDetails(\Temporal\Api\Common\V1\Payloads|null $var)
    {
        $this->last_heartbeat_details = $var;

        return $this;
    }

    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @return \Temporal\Api\Common\V1\WorkerVersionStamp|null
     * @deprecated
     */
    public function getWorkerVersion()
    {
        if (isset($this->worker_version)) {
            @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        }
        return $this->worker_version;
    }

    public function hasWorkerVersion()
    {
        if (isset($this->worker_version)) {
            @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->worker_version);
    }

    public function clearWorkerVersion()
    {
        @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        unset($this->worker_version);
    }

    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @param \Temporal\Api\Common\V1\WorkerVersionStamp $var
     * @return $this
     * @deprecated
     */
    public function setWorkerVersion(\Temporal\Api\Common\V1\WorkerVersionStamp|null $var)
    {
        @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        $this->worker_version = $var;

        return $this;
    }

    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 7 [json_name = "deployment", deprecated = true];</code>
     * @return \Temporal\Api\Deployment\V1\Deployment|null
     * @deprecated
     */
    public function getDeployment()
    {
        if (isset($this->deployment)) {
            @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        }
        return $this->deployment;
    }

    public function hasDeployment()
    {
        if (isset($this->deployment)) {
            @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->deployment);
    }

    public function clearDeployment()
    {
        @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        unset($this->deployment);
    }

    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 7 [json_name = "deployment", deprecated = true];</code>
     * @param \Temporal\Api\Deployment\V1\Deployment $var
     * @return $this
     * @deprecated
     */
    public function setDeployment(\Temporal\Api\Deployment\V1\Deployment|null $var)
    {
        @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        $this->deployment = $var;

        return $this;
    }

    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 8 [json_name = "deploymentOptions"];</code>
     * @return \Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null
     */
    public function getDeploymentOptions()
    {
        return $this->deployment_options;
    }

    public function hasDeploymentOptions()
    {
        return isset($this->deployment_options);
    }

    public function clearDeploymentOptions()
    {
        unset($this->deployment_options);
    }

    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 8 [json_name = "deploymentOptions"];</code>
     * @param \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $var
     * @return $this
     */
    public function setDeploymentOptions(\Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null $var)
    {
        $this->deployment_options = $var;

        return $this;
    }

}

