<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest</code>
 */
class RespondWorkflowTaskCompletedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The task token as received in `PollWorkflowTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     */
    protected $task_token = '';
    /**
     * A list of commands generated when driving the workflow code in response to the new task
     *
     * Generated from protobuf field <code>repeated .temporal.api.command.v1.Command commands = 2 [json_name = "commands"];</code>
     */
    private $commands;
    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * May be set by workers to indicate that the worker desires future tasks to be provided with
     * incremental history on a sticky queue.
     *
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.StickyExecutionAttributes sticky_attributes = 4 [json_name = "stickyAttributes"];</code>
     */
    protected $sticky_attributes = null;
    /**
     * If set, the worker wishes to immediately receive the next workflow task as a response to
     * this completion. This can save on polling round-trips.
     *
     * Generated from protobuf field <code>bool return_new_workflow_task = 5 [json_name = "returnNewWorkflowTask"];</code>
     */
    protected $return_new_workflow_task = false;
    /**
     * Can be used to *force* creation of a new workflow task, even if no commands have resolved or
     * one would not otherwise have been generated. This is used when the worker knows it is doing
     * something useful, but cannot complete it within the workflow task timeout. Local activities
     * which run for longer than the task timeout being the prime example.
     *
     * Generated from protobuf field <code>bool force_create_new_workflow_task = 6 [json_name = "forceCreateNewWorkflowTask"];</code>
     */
    protected $force_create_new_workflow_task = false;
    /**
     * Deprecated. Use `deployment_options` instead.
     * Worker process' unique binary id
     *
     * Generated from protobuf field <code>string binary_checksum = 7 [json_name = "binaryChecksum", deprecated = true];</code>
     * @deprecated
     */
    protected $binary_checksum = '';
    /**
     * Responses to the `queries` field in the task being responded to
     *
     * Generated from protobuf field <code>map<string, .temporal.api.query.v1.WorkflowQueryResult> query_results = 8 [json_name = "queryResults"];</code>
     */
    private $query_results;
    /**
     * Generated from protobuf field <code>string namespace = 9 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` and `versioning_behavior` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version_stamp = 10 [json_name = "workerVersionStamp", deprecated = true];</code>
     * @deprecated
     */
    protected $worker_version_stamp = null;
    /**
     * Protocol messages piggybacking on a WFT as a transport
     *
     * Generated from protobuf field <code>repeated .temporal.api.protocol.v1.Message messages = 11 [json_name = "messages"];</code>
     */
    private $messages;
    /**
     * Data the SDK wishes to record for itself, but server need not interpret, and does not
     * directly impact workflow state.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.WorkflowTaskCompletedMetadata sdk_metadata = 12 [json_name = "sdkMetadata"];</code>
     */
    protected $sdk_metadata = null;
    /**
     * Local usage data collected for metering
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.MeteringMetadata metering_metadata = 13 [json_name = "meteringMetadata"];</code>
     */
    protected $metering_metadata = null;
    /**
     * All capabilities the SDK supports.
     *
     * Generated from protobuf field <code>.temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest.Capabilities capabilities = 14 [json_name = "capabilities"];</code>
     */
    protected $capabilities = null;
    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 15 [json_name = "deployment", deprecated = true];</code>
     * @deprecated
     */
    protected $deployment = null;
    /**
     * Versioning behavior of this workflow execution as set on the worker that completed this task.
     * UNSPECIFIED means versioning is not enabled in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 16 [json_name = "versioningBehavior"];</code>
     */
    protected $versioning_behavior = 0;
    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 17 [json_name = "deploymentOptions"];</code>
     */
    protected $deployment_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_token
     *           The task token as received in `PollWorkflowTaskQueueResponse`
     *     @type \Temporal\Api\Command\V1\Command[] $commands
     *           A list of commands generated when driving the workflow code in response to the new task
     *     @type string $identity
     *           The identity of the worker/client
     *     @type \Temporal\Api\Taskqueue\V1\StickyExecutionAttributes $sticky_attributes
     *           May be set by workers to indicate that the worker desires future tasks to be provided with
     *           incremental history on a sticky queue.
     *     @type bool $return_new_workflow_task
     *           If set, the worker wishes to immediately receive the next workflow task as a response to
     *           this completion. This can save on polling round-trips.
     *     @type bool $force_create_new_workflow_task
     *           Can be used to *force* creation of a new workflow task, even if no commands have resolved or
     *           one would not otherwise have been generated. This is used when the worker knows it is doing
     *           something useful, but cannot complete it within the workflow task timeout. Local activities
     *           which run for longer than the task timeout being the prime example.
     *     @type string $binary_checksum
     *           Deprecated. Use `deployment_options` instead.
     *           Worker process' unique binary id
     *     @type array|\Google\Protobuf\Internal\MapField $query_results
     *           Responses to the `queries` field in the task being responded to
     *     @type string $namespace
     *     @type \Temporal\Api\Common\V1\WorkerVersionStamp $worker_version_stamp
     *           Version info of the worker who processed this task. This message's `build_id` field should
     *           always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     *           field to true. See message docstrings for more.
     *           Deprecated. Use `deployment_options` and `versioning_behavior` instead.
     *     @type \Temporal\Api\Protocol\V1\Message[] $messages
     *           Protocol messages piggybacking on a WFT as a transport
     *     @type \Temporal\Api\Sdk\V1\WorkflowTaskCompletedMetadata $sdk_metadata
     *           Data the SDK wishes to record for itself, but server need not interpret, and does not
     *           directly impact workflow state.
     *     @type \Temporal\Api\Common\V1\MeteringMetadata $metering_metadata
     *           Local usage data collected for metering
     *     @type \Temporal\Api\Workflowservice\V1\RespondWorkflowTaskCompletedRequest\Capabilities $capabilities
     *           All capabilities the SDK supports.
     *     @type \Temporal\Api\Deployment\V1\Deployment $deployment
     *           Deployment info of the worker that completed this task. Must be present if user has set
     *           `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     *           Deprecated. Replaced with `deployment_options`.
     *     @type int $versioning_behavior
     *           Versioning behavior of this workflow execution as set on the worker that completed this task.
     *           UNSPECIFIED means versioning is not enabled in the worker.
     *     @type \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $deployment_options
     *           Worker deployment options that user has set in the worker.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * The task token as received in `PollWorkflowTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @return string
     */
    public function getTaskToken()
    {
        return $this->task_token;
    }

    /**
     * The task token as received in `PollWorkflowTaskQueueResponse`
     *
     * Generated from protobuf field <code>bytes task_token = 1 [json_name = "taskToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setTaskToken(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->task_token = $var;

        return $this;
    }

    /**
     * A list of commands generated when driving the workflow code in response to the new task
     *
     * Generated from protobuf field <code>repeated .temporal.api.command.v1.Command commands = 2 [json_name = "commands"];</code>
     * @return RepeatedField<\Temporal\Api\Command\V1\Command>
     */
    public function getCommands()
    {
        return $this->commands;
    }

    /**
     * A list of commands generated when driving the workflow code in response to the new task
     *
     * Generated from protobuf field <code>repeated .temporal.api.command.v1.Command commands = 2 [json_name = "commands"];</code>
     * @param \Temporal\Api\Command\V1\Command[] $var
     * @return $this
     */
    public function setCommands(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Command\V1\Command::class);
        $this->commands = $arr;

        return $this;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The identity of the worker/client
     *
     * Generated from protobuf field <code>string identity = 3 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * May be set by workers to indicate that the worker desires future tasks to be provided with
     * incremental history on a sticky queue.
     *
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.StickyExecutionAttributes sticky_attributes = 4 [json_name = "stickyAttributes"];</code>
     * @return \Temporal\Api\Taskqueue\V1\StickyExecutionAttributes|null
     */
    public function getStickyAttributes()
    {
        return $this->sticky_attributes;
    }

    public function hasStickyAttributes()
    {
        return isset($this->sticky_attributes);
    }

    public function clearStickyAttributes()
    {
        unset($this->sticky_attributes);
    }

    /**
     * May be set by workers to indicate that the worker desires future tasks to be provided with
     * incremental history on a sticky queue.
     *
     * Generated from protobuf field <code>.temporal.api.taskqueue.v1.StickyExecutionAttributes sticky_attributes = 4 [json_name = "stickyAttributes"];</code>
     * @param \Temporal\Api\Taskqueue\V1\StickyExecutionAttributes $var
     * @return $this
     */
    public function setStickyAttributes(\Temporal\Api\Taskqueue\V1\StickyExecutionAttributes|null $var)
    {
        $this->sticky_attributes = $var;

        return $this;
    }

    /**
     * If set, the worker wishes to immediately receive the next workflow task as a response to
     * this completion. This can save on polling round-trips.
     *
     * Generated from protobuf field <code>bool return_new_workflow_task = 5 [json_name = "returnNewWorkflowTask"];</code>
     * @return bool
     */
    public function getReturnNewWorkflowTask()
    {
        return $this->return_new_workflow_task;
    }

    /**
     * If set, the worker wishes to immediately receive the next workflow task as a response to
     * this completion. This can save on polling round-trips.
     *
     * Generated from protobuf field <code>bool return_new_workflow_task = 5 [json_name = "returnNewWorkflowTask"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnNewWorkflowTask(bool $var)
    {
        $this->return_new_workflow_task = $var;

        return $this;
    }

    /**
     * Can be used to *force* creation of a new workflow task, even if no commands have resolved or
     * one would not otherwise have been generated. This is used when the worker knows it is doing
     * something useful, but cannot complete it within the workflow task timeout. Local activities
     * which run for longer than the task timeout being the prime example.
     *
     * Generated from protobuf field <code>bool force_create_new_workflow_task = 6 [json_name = "forceCreateNewWorkflowTask"];</code>
     * @return bool
     */
    public function getForceCreateNewWorkflowTask()
    {
        return $this->force_create_new_workflow_task;
    }

    /**
     * Can be used to *force* creation of a new workflow task, even if no commands have resolved or
     * one would not otherwise have been generated. This is used when the worker knows it is doing
     * something useful, but cannot complete it within the workflow task timeout. Local activities
     * which run for longer than the task timeout being the prime example.
     *
     * Generated from protobuf field <code>bool force_create_new_workflow_task = 6 [json_name = "forceCreateNewWorkflowTask"];</code>
     * @param bool $var
     * @return $this
     */
    public function setForceCreateNewWorkflowTask(bool $var)
    {
        $this->force_create_new_workflow_task = $var;

        return $this;
    }

    /**
     * Deprecated. Use `deployment_options` instead.
     * Worker process' unique binary id
     *
     * Generated from protobuf field <code>string binary_checksum = 7 [json_name = "binaryChecksum", deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getBinaryChecksum()
    {
        if ($this->binary_checksum !== '') {
            @trigger_error('binary_checksum is deprecated.', E_USER_DEPRECATED);
        }
        return $this->binary_checksum;
    }

    /**
     * Deprecated. Use `deployment_options` instead.
     * Worker process' unique binary id
     *
     * Generated from protobuf field <code>string binary_checksum = 7 [json_name = "binaryChecksum", deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setBinaryChecksum(string $var)
    {
        @trigger_error('binary_checksum is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->binary_checksum = $var;

        return $this;
    }

    /**
     * Responses to the `queries` field in the task being responded to
     *
     * Generated from protobuf field <code>map<string, .temporal.api.query.v1.WorkflowQueryResult> query_results = 8 [json_name = "queryResults"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getQueryResults()
    {
        return $this->query_results;
    }

    /**
     * Responses to the `queries` field in the task being responded to
     *
     * Generated from protobuf field <code>map<string, .temporal.api.query.v1.WorkflowQueryResult> query_results = 8 [json_name = "queryResults"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setQueryResults(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Query\V1\WorkflowQueryResult::class);
        $this->query_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 9 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 9 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` and `versioning_behavior` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version_stamp = 10 [json_name = "workerVersionStamp", deprecated = true];</code>
     * @return \Temporal\Api\Common\V1\WorkerVersionStamp|null
     * @deprecated
     */
    public function getWorkerVersionStamp()
    {
        if (isset($this->worker_version_stamp)) {
            @trigger_error('worker_version_stamp is deprecated.', E_USER_DEPRECATED);
        }
        return $this->worker_version_stamp;
    }

    public function hasWorkerVersionStamp()
    {
        if (isset($this->worker_version_stamp)) {
            @trigger_error('worker_version_stamp is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->worker_version_stamp);
    }

    public function clearWorkerVersionStamp()
    {
        @trigger_error('worker_version_stamp is deprecated.', E_USER_DEPRECATED);
        unset($this->worker_version_stamp);
    }

    /**
     * Version info of the worker who processed this task. This message's `build_id` field should
     * always be set by SDKs. Workers opting into versioning will also set the `use_versioning`
     * field to true. See message docstrings for more.
     * Deprecated. Use `deployment_options` and `versioning_behavior` instead.
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version_stamp = 10 [json_name = "workerVersionStamp", deprecated = true];</code>
     * @param \Temporal\Api\Common\V1\WorkerVersionStamp $var
     * @return $this
     * @deprecated
     */
    public function setWorkerVersionStamp(\Temporal\Api\Common\V1\WorkerVersionStamp|null $var)
    {
        @trigger_error('worker_version_stamp is deprecated.', E_USER_DEPRECATED);
        $this->worker_version_stamp = $var;

        return $this;
    }

    /**
     * Protocol messages piggybacking on a WFT as a transport
     *
     * Generated from protobuf field <code>repeated .temporal.api.protocol.v1.Message messages = 11 [json_name = "messages"];</code>
     * @return RepeatedField<\Temporal\Api\Protocol\V1\Message>
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Protocol messages piggybacking on a WFT as a transport
     *
     * Generated from protobuf field <code>repeated .temporal.api.protocol.v1.Message messages = 11 [json_name = "messages"];</code>
     * @param \Temporal\Api\Protocol\V1\Message[] $var
     * @return $this
     */
    public function setMessages(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Protocol\V1\Message::class);
        $this->messages = $arr;

        return $this;
    }

    /**
     * Data the SDK wishes to record for itself, but server need not interpret, and does not
     * directly impact workflow state.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.WorkflowTaskCompletedMetadata sdk_metadata = 12 [json_name = "sdkMetadata"];</code>
     * @return \Temporal\Api\Sdk\V1\WorkflowTaskCompletedMetadata|null
     */
    public function getSdkMetadata()
    {
        return $this->sdk_metadata;
    }

    public function hasSdkMetadata()
    {
        return isset($this->sdk_metadata);
    }

    public function clearSdkMetadata()
    {
        unset($this->sdk_metadata);
    }

    /**
     * Data the SDK wishes to record for itself, but server need not interpret, and does not
     * directly impact workflow state.
     *
     * Generated from protobuf field <code>.temporal.api.sdk.v1.WorkflowTaskCompletedMetadata sdk_metadata = 12 [json_name = "sdkMetadata"];</code>
     * @param \Temporal\Api\Sdk\V1\WorkflowTaskCompletedMetadata $var
     * @return $this
     */
    public function setSdkMetadata(\Temporal\Api\Sdk\V1\WorkflowTaskCompletedMetadata|null $var)
    {
        $this->sdk_metadata = $var;

        return $this;
    }

    /**
     * Local usage data collected for metering
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.MeteringMetadata metering_metadata = 13 [json_name = "meteringMetadata"];</code>
     * @return \Temporal\Api\Common\V1\MeteringMetadata|null
     */
    public function getMeteringMetadata()
    {
        return $this->metering_metadata;
    }

    public function hasMeteringMetadata()
    {
        return isset($this->metering_metadata);
    }

    public function clearMeteringMetadata()
    {
        unset($this->metering_metadata);
    }

    /**
     * Local usage data collected for metering
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.MeteringMetadata metering_metadata = 13 [json_name = "meteringMetadata"];</code>
     * @param \Temporal\Api\Common\V1\MeteringMetadata $var
     * @return $this
     */
    public function setMeteringMetadata(\Temporal\Api\Common\V1\MeteringMetadata|null $var)
    {
        $this->metering_metadata = $var;

        return $this;
    }

    /**
     * All capabilities the SDK supports.
     *
     * Generated from protobuf field <code>.temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest.Capabilities capabilities = 14 [json_name = "capabilities"];</code>
     * @return \Temporal\Api\Workflowservice\V1\RespondWorkflowTaskCompletedRequest\Capabilities|null
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    public function hasCapabilities()
    {
        return isset($this->capabilities);
    }

    public function clearCapabilities()
    {
        unset($this->capabilities);
    }

    /**
     * All capabilities the SDK supports.
     *
     * Generated from protobuf field <code>.temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest.Capabilities capabilities = 14 [json_name = "capabilities"];</code>
     * @param \Temporal\Api\Workflowservice\V1\RespondWorkflowTaskCompletedRequest\Capabilities $var
     * @return $this
     */
    public function setCapabilities(\Temporal\Api\Workflowservice\V1\RespondWorkflowTaskCompletedRequest\Capabilities|null $var)
    {
        $this->capabilities = $var;

        return $this;
    }

    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 15 [json_name = "deployment", deprecated = true];</code>
     * @return \Temporal\Api\Deployment\V1\Deployment|null
     * @deprecated
     */
    public function getDeployment()
    {
        if (isset($this->deployment)) {
            @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        }
        return $this->deployment;
    }

    public function hasDeployment()
    {
        if (isset($this->deployment)) {
            @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->deployment);
    }

    public function clearDeployment()
    {
        @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        unset($this->deployment);
    }

    /**
     * Deployment info of the worker that completed this task. Must be present if user has set
     * `WorkerDeploymentOptions` regardless of versioning being enabled or not.
     * Deprecated. Replaced with `deployment_options`.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.Deployment deployment = 15 [json_name = "deployment", deprecated = true];</code>
     * @param \Temporal\Api\Deployment\V1\Deployment $var
     * @return $this
     * @deprecated
     */
    public function setDeployment(\Temporal\Api\Deployment\V1\Deployment|null $var)
    {
        @trigger_error('deployment is deprecated.', E_USER_DEPRECATED);
        $this->deployment = $var;

        return $this;
    }

    /**
     * Versioning behavior of this workflow execution as set on the worker that completed this task.
     * UNSPECIFIED means versioning is not enabled in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 16 [json_name = "versioningBehavior"];</code>
     * @return int one of the values in {@see \Temporal\Api\Enums\V1\VersioningBehavior}
     */
    public function getVersioningBehavior()
    {
        return $this->versioning_behavior;
    }

    /**
     * Versioning behavior of this workflow execution as set on the worker that completed this task.
     * UNSPECIFIED means versioning is not enabled in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.VersioningBehavior versioning_behavior = 16 [json_name = "versioningBehavior"];</code>
     * @param int $var one of the values in {@see \Temporal\Api\Enums\V1\VersioningBehavior}
     * @return $this
     */
    public function setVersioningBehavior(int $var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\VersioningBehavior::class);
        $this->versioning_behavior = $var;

        return $this;
    }

    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 17 [json_name = "deploymentOptions"];</code>
     * @return \Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null
     */
    public function getDeploymentOptions()
    {
        return $this->deployment_options;
    }

    public function hasDeploymentOptions()
    {
        return isset($this->deployment_options);
    }

    public function clearDeploymentOptions()
    {
        unset($this->deployment_options);
    }

    /**
     * Worker deployment options that user has set in the worker.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentOptions deployment_options = 17 [json_name = "deploymentOptions"];</code>
     * @param \Temporal\Api\Deployment\V1\WorkerDeploymentOptions $var
     * @return $this
     */
    public function setDeploymentOptions(\Temporal\Api\Deployment\V1\WorkerDeploymentOptions|null $var)
    {
        $this->deployment_options = $var;

        return $this;
    }

}

