<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websockets/v2/websockets.proto

namespace RoadRunner\Websockets\DTO\V2\GPBMetadata;

class Websockets
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA7\x02\x0A\x1Ewebsockets/v2/websockets.proto\x12\x0Dwebsockets.v2\"^\x0A\x10WebsocketMessage\x12\x18\x0A\x07command\x18\x01 \x01(\x09R\x07command\x12\x16\x0A\x06topics\x18\x02 \x03(\x09R\x06topics\x12\x18\x0A\x07payload\x18\x03 \x01(\x0CR\x07payloadB\x8D\x01ZAgithub.com/roadrunner-server/api-go/v6/websockets/v2;websocketsV2\xCA\x02\x1CRoadRunner\\Websockets\\DTO\\V2\xE2\x02(RoadRunner\\Websockets\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

