<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/common/v1/message.proto

namespace Temporal\Api\Common\V1\Link;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.common.v1.Link.WorkflowEvent</code>
 */
class WorkflowEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     */
    protected $workflow_id = '';
    /**
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     */
    protected $run_id = '';
    protected $reference;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $workflow_id
     *     @type string $run_id
     *     @type \Temporal\Api\Common\V1\Link\WorkflowEvent\EventReference $event_ref
     *     @type \Temporal\Api\Common\V1\Link\WorkflowEvent\RequestIdReference $request_id_ref
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Common\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return string
     */
    public function getWorkflowId()
    {
        return $this->workflow_id;
    }

    /**
     * Generated from protobuf field <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @param string $var
     * @return $this
     */
    public function setWorkflowId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->workflow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     * @return string
     */
    public function getRunId()
    {
        return $this->run_id;
    }

    /**
     * Generated from protobuf field <code>string run_id = 3 [json_name = "runId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRunId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->run_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Link.WorkflowEvent.EventReference event_ref = 100 [json_name = "eventRef"];</code>
     * @return \Temporal\Api\Common\V1\Link\WorkflowEvent\EventReference|null
     */
    public function getEventRef()
    {
        return $this->readOneof(100);
    }

    public function hasEventRef()
    {
        return $this->hasOneof(100);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Link.WorkflowEvent.EventReference event_ref = 100 [json_name = "eventRef"];</code>
     * @param \Temporal\Api\Common\V1\Link\WorkflowEvent\EventReference $var
     * @return $this
     */
    public function setEventRef(\Temporal\Api\Common\V1\Link\WorkflowEvent\EventReference|null $var)
    {
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Link.WorkflowEvent.RequestIdReference request_id_ref = 101 [json_name = "requestIdRef"];</code>
     * @return \Temporal\Api\Common\V1\Link\WorkflowEvent\RequestIdReference|null
     */
    public function getRequestIdRef()
    {
        return $this->readOneof(101);
    }

    public function hasRequestIdRef()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Link.WorkflowEvent.RequestIdReference request_id_ref = 101 [json_name = "requestIdRef"];</code>
     * @param \Temporal\Api\Common\V1\Link\WorkflowEvent\RequestIdReference $var
     * @return $this
     */
    public function setRequestIdRef(\Temporal\Api\Common\V1\Link\WorkflowEvent\RequestIdReference|null $var)
    {
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getReference()
    {
        return $this->whichOneof("reference");
    }

}

