<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs/v2/request.proto

namespace RoadRunner\Jobs\DTO\V2\GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\Jobs\DTO\V2\GPBMetadata\Jobs::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE5\x04\x0A\x15jobs/v2/request.proto\x12\x07jobs.v2\"4\x0A\x12JobsHandlerRequest\x12\x1E\x0A\x03job\x18\x01 \x01(\x0B2\x0C.jobs.v2.JobR\x03job\"-\x0A\x0BPushRequest\x12\x1E\x0A\x03job\x18\x01 \x01(\x0B2\x0C.jobs.v2.JobR\x03job\"\xCB\x01\x0A\x10PushBatchRequest\x12 \x0A\x04jobs\x18\x01 \x03(\x0B2\x0C.jobs.v2.JobR\x04jobs\x12@\x0A\x07headers\x18\x02 \x03(\x0B2&.jobs.v2.PushBatchRequest.HeadersEntryR\x07headers\x1AS\x0A\x0CHeadersEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12-\x0A\x05value\x18\x02 \x01(\x0B2\x17.jobs.v2.JobHeaderValueR\x05value:\x028\x01\"\x90\x01\x0A\x0EDeclareRequest\x12A\x0A\x08pipeline\x18\x01 \x03(\x0B2%.jobs.v2.DeclareRequest.PipelineEntryR\x08pipeline\x1A;\x0A\x0DPipelineEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0A\x05value\x18\x02 \x01(\x09R\x05value:\x028\x01BuZ5github.com/roadrunner-server/api-go/v6/jobs/v2;jobsV2\xCA\x02\x16RoadRunner\\Jobs\\DTO\\V2\xE2\x02\"RoadRunner\\Jobs\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

