<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     */
    protected $transport = '';
    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     */
    protected $protocol = '';
    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     */
    protected $encoding = '';
    /**
     * Generated from protobuf field <code>bytes data = 10 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string b64data = 11 [json_name = "b64data"];</code>
     */
    protected $b64data = '';
    /**
     * Generated from protobuf field <code>string name = 12 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string version = 13 [json_name = "version"];</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>repeated string channels = 14 [json_name = "channels"];</code>
     */
    private $channels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client
     *     @type string $transport
     *     @type string $protocol
     *     @type string $encoding
     *     @type string $data
     *     @type string $b64data
     *     @type string $name
     *     @type string $version
     *     @type string[] $channels
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransport(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->transport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @return string
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @param string $var
     * @return $this
     */
    public function setEncoding(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->encoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 10 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 10 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64data = 11 [json_name = "b64data"];</code>
     * @return string
     */
    public function getB64Data()
    {
        return $this->b64data;
    }

    /**
     * Generated from protobuf field <code>string b64data = 11 [json_name = "b64data"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Data(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->b64data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 12 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 12 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 13 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 13 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string channels = 14 [json_name = "channels"];</code>
     * @return RepeatedField<string>
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Generated from protobuf field <code>repeated string channels = 14 [json_name = "channels"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setChannels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->channels = $arr;

        return $this;
    }

}

