<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.RefreshResult</code>
 */
class RefreshResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool expired = 1 [json_name = "expired"];</code>
     */
    protected $expired = false;
    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     */
    protected $expire_at = 0;
    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     */
    protected $info = '';
    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     */
    protected $b64info = '';
    /**
     * Generated from protobuf field <code>bytes meta = 5 [json_name = "meta"];</code>
     */
    protected $meta = '';
    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 6 [json_name = "caps"];</code>
     */
    private $caps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $expired
     *     @type int|string $expire_at
     *     @type string $info
     *     @type string $b64info
     *     @type string $meta
     *     @type \RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability[] $caps
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool expired = 1 [json_name = "expired"];</code>
     * @return bool
     */
    public function getExpired()
    {
        return $this->expired;
    }

    /**
     * Generated from protobuf field <code>bool expired = 1 [json_name = "expired"];</code>
     * @param bool $var
     * @return $this
     */
    public function setExpired(bool $var)
    {
        $this->expired = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     * @return int|string
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 2 [json_name = "expireAt"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>bytes info = 3 [json_name = "info"];</code>
     * @param string $var
     * @return $this
     */
    public function setInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     * @return string
     */
    public function getB64Info()
    {
        return $this->b64info;
    }

    /**
     * Generated from protobuf field <code>string b64info = 4 [json_name = "b64info"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Info(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->b64info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 5 [json_name = "meta"];</code>
     * @return string
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 5 [json_name = "meta"];</code>
     * @param string $var
     * @return $this
     */
    public function setMeta(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 6 [json_name = "caps"];</code>
     * @return RepeatedField<\RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability>
     */
    public function getCaps()
    {
        return $this->caps;
    }

    /**
     * Generated from protobuf field <code>repeated .centrifugal.centrifugo.proxy.ChannelsCapability caps = 6 [json_name = "caps"];</code>
     * @param \RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability[] $var
     * @return $this
     */
    public function setCaps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Centrifugal\Proxy\DTO\V1\ChannelsCapability::class);
        $this->caps = $arr;

        return $this;
    }

}

