<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/proxy/v1/proxy.proto

namespace RoadRunner\Centrifugal\Proxy\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.proxy.RPCRequest</code>
 */
class RPCRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     */
    protected $transport = '';
    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     */
    protected $protocol = '';
    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     */
    protected $encoding = '';
    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>string method = 11 [json_name = "method"];</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>bytes data = 12 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string b64data = 13 [json_name = "b64data"];</code>
     */
    protected $b64data = '';
    /**
     * Generated from protobuf field <code>bytes meta = 14 [json_name = "meta"];</code>
     */
    protected $meta = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client
     *     @type string $transport
     *     @type string $protocol
     *     @type string $encoding
     *     @type string $user
     *     @type string $method
     *     @type string $data
     *     @type string $b64data
     *     @type string $meta
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\Proxy\DTO\V1\GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 1 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Generated from protobuf field <code>string transport = 2 [json_name = "transport"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransport(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->transport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 3 [json_name = "protocol"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @return string
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    /**
     * Generated from protobuf field <code>string encoding = 4 [json_name = "encoding"];</code>
     * @param string $var
     * @return $this
     */
    public function setEncoding(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->encoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 10 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 11 [json_name = "method"];</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 11 [json_name = "method"];</code>
     * @param string $var
     * @return $this
     */
    public function setMethod(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 12 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 12 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64data = 13 [json_name = "b64data"];</code>
     * @return string
     */
    public function getB64Data()
    {
        return $this->b64data;
    }

    /**
     * Generated from protobuf field <code>string b64data = 13 [json_name = "b64data"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Data(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->b64data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 14 [json_name = "meta"];</code>
     * @return string
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>bytes meta = 14 [json_name = "meta"];</code>
     * @param string $var
     * @return $this
     */
    public function setMeta(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->meta = $var;

        return $this;
    }

}

