<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status/v2/response.proto

namespace RoadRunner\Status\DTO\V2\GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEC\x01\x0A\x18status/v2/response.proto\x12\x09status.v2\">\x0A\x0EStatusResponse\x12\x12\x0A\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\x0A\x07message\x18\x02 \x01(\x09R\x07messageB}Z9github.com/roadrunner-server/api-go/v6/status/v2;statusV2\xCA\x02\x18RoadRunner\\Status\\DTO\\V2\xE2\x02\$RoadRunner\\Status\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

