<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/history/v1/message.proto

namespace Temporal\Api\History\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.history.v1.ActivityTaskFailedEventAttributes</code>
 */
class ActivityTaskFailedEventAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Failure details
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 1 [json_name = "failure"];</code>
     */
    protected $failure = null;
    /**
     * The id of the `ACTIVITY_TASK_SCHEDULED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 scheduled_event_id = 2 [json_name = "scheduledEventId"];</code>
     */
    protected $scheduled_event_id = 0;
    /**
     * The id of the `ACTIVITY_TASK_STARTED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 started_event_id = 3 [json_name = "startedEventId"];</code>
     */
    protected $started_event_id = 0;
    /**
     * id of the worker that failed this task
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.RetryState retry_state = 5 [json_name = "retryState"];</code>
     */
    protected $retry_state = 0;
    /**
     * Version info of the worker who processed this workflow task.
     * Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @deprecated
     */
    protected $worker_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Failure\V1\Failure $failure
     *           Failure details
     *     @type int|string $scheduled_event_id
     *           The id of the `ACTIVITY_TASK_SCHEDULED` event this failure corresponds to
     *     @type int|string $started_event_id
     *           The id of the `ACTIVITY_TASK_STARTED` event this failure corresponds to
     *     @type string $identity
     *           id of the worker that failed this task
     *     @type int $retry_state
     *     @type \Temporal\Api\Common\V1\WorkerVersionStamp $worker_version
     *           Version info of the worker who processed this workflow task.
     *           Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\History\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Failure details
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 1 [json_name = "failure"];</code>
     * @return \Temporal\Api\Failure\V1\Failure|null
     */
    public function getFailure()
    {
        return $this->failure;
    }

    public function hasFailure()
    {
        return isset($this->failure);
    }

    public function clearFailure()
    {
        unset($this->failure);
    }

    /**
     * Failure details
     *
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure failure = 1 [json_name = "failure"];</code>
     * @param \Temporal\Api\Failure\V1\Failure $var
     * @return $this
     */
    public function setFailure(\Temporal\Api\Failure\V1\Failure|null $var)
    {
        $this->failure = $var;

        return $this;
    }

    /**
     * The id of the `ACTIVITY_TASK_SCHEDULED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 scheduled_event_id = 2 [json_name = "scheduledEventId"];</code>
     * @return int|string
     */
    public function getScheduledEventId()
    {
        return $this->scheduled_event_id;
    }

    /**
     * The id of the `ACTIVITY_TASK_SCHEDULED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 scheduled_event_id = 2 [json_name = "scheduledEventId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setScheduledEventId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->scheduled_event_id = $var;

        return $this;
    }

    /**
     * The id of the `ACTIVITY_TASK_STARTED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 started_event_id = 3 [json_name = "startedEventId"];</code>
     * @return int|string
     */
    public function getStartedEventId()
    {
        return $this->started_event_id;
    }

    /**
     * The id of the `ACTIVITY_TASK_STARTED` event this failure corresponds to
     *
     * Generated from protobuf field <code>int64 started_event_id = 3 [json_name = "startedEventId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartedEventId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->started_event_id = $var;

        return $this;
    }

    /**
     * id of the worker that failed this task
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * id of the worker that failed this task
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.RetryState retry_state = 5 [json_name = "retryState"];</code>
     * @return int one of the values in {@see \Temporal\Api\Enums\V1\RetryState}
     */
    public function getRetryState()
    {
        return $this->retry_state;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.RetryState retry_state = 5 [json_name = "retryState"];</code>
     * @param int $var one of the values in {@see \Temporal\Api\Enums\V1\RetryState}
     * @return $this
     */
    public function setRetryState(int $var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\RetryState::class);
        $this->retry_state = $var;

        return $this;
    }

    /**
     * Version info of the worker who processed this workflow task.
     * Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @return \Temporal\Api\Common\V1\WorkerVersionStamp|null
     * @deprecated
     */
    public function getWorkerVersion()
    {
        if (isset($this->worker_version)) {
            @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        }
        return $this->worker_version;
    }

    public function hasWorkerVersion()
    {
        if (isset($this->worker_version)) {
            @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->worker_version);
    }

    public function clearWorkerVersion()
    {
        @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        unset($this->worker_version);
    }

    /**
     * Version info of the worker who processed this workflow task.
     * Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]
     *
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkerVersionStamp worker_version = 6 [json_name = "workerVersion", deprecated = true];</code>
     * @param \Temporal\Api\Common\V1\WorkerVersionStamp $var
     * @return $this
     * @deprecated
     */
    public function setWorkerVersion(\Temporal\Api\Common\V1\WorkerVersionStamp|null $var)
    {
        @trigger_error('worker_version is deprecated.', E_USER_DEPRECATED);
        $this->worker_version = $var;

        return $this;
    }

}

