<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/history/v1/message.proto

namespace Temporal\Api\History\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>temporal.api.history.v1.TimerCanceledEventAttributes</code>
 */
class TimerCanceledEventAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Will match the `timer_id` from `TIMER_STARTED` event for this timer
     *
     * Generated from protobuf field <code>string timer_id = 1 [json_name = "timerId"];</code>
     */
    protected $timer_id = '';
    /**
     * The id of the `TIMER_STARTED` event itself
     *
     * Generated from protobuf field <code>int64 started_event_id = 2 [json_name = "startedEventId"];</code>
     */
    protected $started_event_id = 0;
    /**
     * The `WORKFLOW_TASK_COMPLETED` event which this command was reported with
     *
     * Generated from protobuf field <code>int64 workflow_task_completed_event_id = 3 [json_name = "workflowTaskCompletedEventId"];</code>
     */
    protected $workflow_task_completed_event_id = 0;
    /**
     * The id of the worker who requested this cancel
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     */
    protected $identity = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $timer_id
     *           Will match the `timer_id` from `TIMER_STARTED` event for this timer
     *     @type int|string $started_event_id
     *           The id of the `TIMER_STARTED` event itself
     *     @type int|string $workflow_task_completed_event_id
     *           The `WORKFLOW_TASK_COMPLETED` event which this command was reported with
     *     @type string $identity
     *           The id of the worker who requested this cancel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\History\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Will match the `timer_id` from `TIMER_STARTED` event for this timer
     *
     * Generated from protobuf field <code>string timer_id = 1 [json_name = "timerId"];</code>
     * @return string
     */
    public function getTimerId()
    {
        return $this->timer_id;
    }

    /**
     * Will match the `timer_id` from `TIMER_STARTED` event for this timer
     *
     * Generated from protobuf field <code>string timer_id = 1 [json_name = "timerId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTimerId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->timer_id = $var;

        return $this;
    }

    /**
     * The id of the `TIMER_STARTED` event itself
     *
     * Generated from protobuf field <code>int64 started_event_id = 2 [json_name = "startedEventId"];</code>
     * @return int|string
     */
    public function getStartedEventId()
    {
        return $this->started_event_id;
    }

    /**
     * The id of the `TIMER_STARTED` event itself
     *
     * Generated from protobuf field <code>int64 started_event_id = 2 [json_name = "startedEventId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartedEventId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->started_event_id = $var;

        return $this;
    }

    /**
     * The `WORKFLOW_TASK_COMPLETED` event which this command was reported with
     *
     * Generated from protobuf field <code>int64 workflow_task_completed_event_id = 3 [json_name = "workflowTaskCompletedEventId"];</code>
     * @return int|string
     */
    public function getWorkflowTaskCompletedEventId()
    {
        return $this->workflow_task_completed_event_id;
    }

    /**
     * The `WORKFLOW_TASK_COMPLETED` event which this command was reported with
     *
     * Generated from protobuf field <code>int64 workflow_task_completed_event_id = 3 [json_name = "workflowTaskCompletedEventId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorkflowTaskCompletedEventId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->workflow_task_completed_event_id = $var;

        return $this;
    }

    /**
     * The id of the worker who requested this cancel
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * The id of the worker who requested this cancel
     *
     * Generated from protobuf field <code>string identity = 4 [json_name = "identity"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

}

