<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v2/request.proto

namespace RoadRunner\Service\DTO\V2\GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x05\x0A\x18service/v2/request.proto\x12\x0Aservice.v2\"\xA5\x03\x0A\x14ServiceCreateRequest\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\x12\x18\x0A\x07command\x18\x02 \x01(\x09R\x07command\x12\x1F\x0A\x0Bprocess_num\x18\x03 \x01(\x03R\x0AprocessNum\x12!\x0A\x0Cexec_timeout\x18\x04 \x01(\x03R\x0BexecTimeout\x12*\x0A\x11remain_after_exit\x18\x05 \x01(\x08R\x0FremainAfterExit\x12;\x0A\x03env\x18\x06 \x03(\x0B2).service.v2.ServiceCreateRequest.EnvEntryR\x03env\x12\x1F\x0A\x0Brestart_sec\x18\x07 \x01(\x04R\x0ArestartSec\x12/\x0A\x14service_name_in_logs\x18\x08 \x01(\x08R\x11serviceNameInLogs\x12(\x0A\x10timeout_stop_sec\x18\x09 \x01(\x04R\x0EtimeoutStopSec\x1A6\x0A\x08EnvEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0A\x05value\x18\x02 \x01(\x09R\x05value:\x028\x01\"(\x0A\x12ServiceInfoRequest\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04nameB\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v2;serviceV2\xCA\x02\x19RoadRunner\\Service\\DTO\\V2\xE2\x02%RoadRunner\\Service\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

