<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v2/response.proto

namespace RoadRunner\Service\DTO\V2\GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\Service\DTO\V2\GPBMetadata\Service::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE5\x02\x0A\x19service/v2/response.proto\x12\x0Aservice.v2\";\x0A\x0FServiceResponse\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message\x12\x0E\x0A\x02ok\x18\x02 \x01(\x08R\x02ok\"H\x0A\x0FServiceStatuses\x125\x0A\x08statuses\x18\x01 \x03(\x0B2\x19.service.v2.ProcessStatusR\x08statuses\")\x0A\x0BServiceList\x12\x1A\x0A\x08services\x18\x01 \x03(\x09R\x08servicesB\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v2;serviceV2\xCA\x02\x19RoadRunner\\Service\\DTO\\V2\xE2\x02%RoadRunner\\Service\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

