<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v2/service.proto

namespace RoadRunner\Service\DTO\V2\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\Common\DTO\V1\GPBMetadata\GrpcStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDF\x02\x0A\x18service/v2/service.proto\x12\x0Aservice.v2\"\xAA\x01\x0A\x0DProcessStatus\x12\x1F\x0A\x0Bcpu_percent\x18\x01 \x01(\x02R\x0AcpuPercent\x12\x10\x0A\x03pid\x18\x02 \x01(\x05R\x03pid\x12!\x0A\x0Cmemory_usage\x18\x03 \x01(\x04R\x0BmemoryUsage\x12\x18\x0A\x07command\x18\x04 \x01(\x09R\x07command\x12)\x0A\x06status\x18\x05 \x01(\x0B2\x11.common.v1.StatusR\x06statusB\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v2;serviceV2\xCA\x02\x19RoadRunner\\Service\\DTO\\V2\xE2\x02%RoadRunner\\Service\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

