<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv/v2/request.proto

namespace RoadRunner\KV\DTO\V2\GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\KV\DTO\V2\GPBMetadata\Kv::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDF\x01\x0A\x13kv/v2/request.proto\x12\x05kv.v2\"J\x0A\x09KvRequest\x12\x18\x0A\x07storage\x18\x01 \x01(\x09R\x07storage\x12#\x0A\x05items\x18\x02 \x03(\x0B2\x0D.kv.v2.KvItemR\x05itemsBmZ1github.com/roadrunner-server/api-go/v6/kv/v2;kvV2\xCA\x02\x14RoadRunner\\KV\\DTO\\V2\xE2\x02 RoadRunner\\KV\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

