<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv/v2/service.proto

namespace RoadRunner\KV\DTO\V2\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\KV\DTO\V2\GPBMetadata\Request::initOnce();
        \RoadRunner\KV\DTO\V2\GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x04\x0A\x13kv/v2/service.proto\x12\x05kv.v2\x1A\x14kv/v2/response.proto2\xD8\x02\x0A\x09KvService\x12/\x0A\x03Has\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\"\x03\x90\x02\x01\x12*\x0A\x03Set\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\x120\x0A\x04MGet\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\"\x03\x90\x02\x01\x12.\x0A\x07MExpire\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\x12/\x0A\x03TTL\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\"\x03\x90\x02\x01\x12-\x0A\x06Delete\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponse\x12,\x0A\x05Clear\x12\x10.kv.v2.KvRequest\x1A\x11.kv.v2.KvResponseBmZ1github.com/roadrunner-server/api-go/v6/kv/v2;kvV2\xCA\x02\x14RoadRunner\\KV\\DTO\\V2\xE2\x02 RoadRunner\\KV\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

