<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: applogger/v2/applogger.proto

namespace RoadRunner\AppLogger\DTO\V2\GPBMetadata;

class Applogger
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xDE\x02\x0A\x1Capplogger/v2/applogger.proto\x12\x0Capplogger.v2\"Y\x0A\x08LogEntry\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message\x123\x0A\x09log_attrs\x18\x02 \x03(\x0B2\x16.applogger.v2.LogAttrsR\x08logAttrs\"2\x0A\x08LogAttrs\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0A\x05value\x18\x02 \x01(\x09R\x05value\"\x0D\x0A\x0BLogResponseB\x89\x01Z?github.com/roadrunner-server/api-go/v6/applogger/v2;apploggerV2\xCA\x02\x1BRoadRunner\\AppLogger\\DTO\\V2\xE2\x02'RoadRunner\\AppLogger\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

