<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: applogger/v2/service.proto

namespace RoadRunner\AppLogger\DTO\V2\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\AppLogger\DTO\V2\GPBMetadata\Applogger::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x92\x07\x0A\x1Aapplogger/v2/service.proto\x12\x0Capplogger.v2\"&\x0A\x0ALogMessage\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message2\xA9\x05\x0A\x10AppLoggerService\x12<\x0A\x05Error\x12\x18.applogger.v2.LogMessage\x1A\x19.applogger.v2.LogResponse\x12E\x0A\x10ErrorWithContext\x12\x16.applogger.v2.LogEntry\x1A\x19.applogger.v2.LogResponse\x12;\x0A\x04Info\x12\x18.applogger.v2.LogMessage\x1A\x19.applogger.v2.LogResponse\x12D\x0A\x0FInfoWithContext\x12\x16.applogger.v2.LogEntry\x1A\x19.applogger.v2.LogResponse\x12>\x0A\x07Warning\x12\x18.applogger.v2.LogMessage\x1A\x19.applogger.v2.LogResponse\x12G\x0A\x12WarningWithContext\x12\x16.applogger.v2.LogEntry\x1A\x19.applogger.v2.LogResponse\x12<\x0A\x05Debug\x12\x18.applogger.v2.LogMessage\x1A\x19.applogger.v2.LogResponse\x12E\x0A\x10DebugWithContext\x12\x16.applogger.v2.LogEntry\x1A\x19.applogger.v2.LogResponse\x12:\x0A\x03Log\x12\x18.applogger.v2.LogMessage\x1A\x19.applogger.v2.LogResponse\x12C\x0A\x0ELogWithContext\x12\x16.applogger.v2.LogEntry\x1A\x19.applogger.v2.LogResponseB\x89\x01Z?github.com/roadrunner-server/api-go/v6/applogger/v2;apploggerV2\xCA\x02\x1BRoadRunner\\AppLogger\\DTO\\V2\xE2\x02'RoadRunner\\AppLogger\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

