<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs/v2/jobs.proto

namespace RoadRunner\Jobs\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * JobHeaderValue represents []string value for the header (map[string][]string)
 *
 * Generated from protobuf message <code>jobs.v2.JobHeaderValue</code>
 */
class JobHeaderValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string values = 1 [json_name = "values"];</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $values
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Jobs\DTO\V2\GPBMetadata\Jobs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string values = 1 [json_name = "values"];</code>
     * @return RepeatedField<string>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated string values = 1 [json_name = "values"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->values = $arr;

        return $this;
    }

}

