<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs/v2/response.proto

namespace RoadRunner\Jobs\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * some endpoints receives nothing
 * all endpoints returns nothing, except error
 *
 * Generated from protobuf message <code>jobs.v2.JobsHandlerResponse</code>
 */
class JobsHandlerResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Jobs\DTO\V2\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

}

