<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs/v2/request.proto

namespace RoadRunner\Jobs\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>jobs.v2.JobsHandlerRequest</code>
 */
class JobsHandlerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.jobs.v2.Job job = 1 [json_name = "job"];</code>
     */
    protected $job = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Jobs\DTO\V2\Job $job
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Jobs\DTO\V2\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.jobs.v2.Job job = 1 [json_name = "job"];</code>
     * @return \RoadRunner\Jobs\DTO\V2\Job|null
     */
    public function getJob()
    {
        return $this->job;
    }

    public function hasJob()
    {
        return isset($this->job);
    }

    public function clearJob()
    {
        unset($this->job);
    }

    /**
     * Generated from protobuf field <code>.jobs.v2.Job job = 1 [json_name = "job"];</code>
     * @param \RoadRunner\Jobs\DTO\V2\Job $var
     * @return $this
     */
    public function setJob(\RoadRunner\Jobs\DTO\V2\Job|null $var)
    {
        $this->job = $var;

        return $this;
    }

}

