<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Collector describes the shape of a single application-defined metric.
 * Mirrors github.com/roadrunner-server/metrics/v6.Collector.
 *
 * Generated from protobuf message <code>metrics.v1.Collector</code>
 */
class Collector extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string subsystem = 2 [json_name = "subsystem"];</code>
     */
    protected $subsystem = '';
    /**
     * Generated from protobuf field <code>.metrics.v1.CollectorType type = 3 [json_name = "type"];</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string help = 4 [json_name = "help"];</code>
     */
    protected $help = '';
    /**
     * Generated from protobuf field <code>repeated string labels = 5 [json_name = "labels"];</code>
     */
    private $labels;
    /**
     * Generated from protobuf field <code>repeated double buckets = 6 [json_name = "buckets"];</code>
     */
    private $buckets;
    /**
     * Generated from protobuf field <code>repeated .metrics.v1.Objective objectives = 7 [json_name = "objectives"];</code>
     */
    private $objectives;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type string $subsystem
     *     @type int $type
     *     @type string $help
     *     @type string[] $labels
     *     @type float[] $buckets
     *     @type \RoadRunner\Metrics\DTO\V1\Objective[] $objectives
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Metrics\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1 [json_name = "namespace"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subsystem = 2 [json_name = "subsystem"];</code>
     * @return string
     */
    public function getSubsystem()
    {
        return $this->subsystem;
    }

    /**
     * Generated from protobuf field <code>string subsystem = 2 [json_name = "subsystem"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubsystem(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->subsystem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.CollectorType type = 3 [json_name = "type"];</code>
     * @return int one of the values in {@see \RoadRunner\Metrics\DTO\V1\CollectorType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.CollectorType type = 3 [json_name = "type"];</code>
     * @param int $var one of the values in {@see \RoadRunner\Metrics\DTO\V1\CollectorType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \RoadRunner\Metrics\DTO\V1\CollectorType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string help = 4 [json_name = "help"];</code>
     * @return string
     */
    public function getHelp()
    {
        return $this->help;
    }

    /**
     * Generated from protobuf field <code>string help = 4 [json_name = "help"];</code>
     * @param string $var
     * @return $this
     */
    public function setHelp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->help = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 5 [json_name = "labels"];</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 5 [json_name = "labels"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double buckets = 6 [json_name = "buckets"];</code>
     * @return RepeatedField<float>
     */
    public function getBuckets()
    {
        return $this->buckets;
    }

    /**
     * Generated from protobuf field <code>repeated double buckets = 6 [json_name = "buckets"];</code>
     * @param float[] $var
     * @return $this
     */
    public function setBuckets(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->buckets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .metrics.v1.Objective objectives = 7 [json_name = "objectives"];</code>
     * @return RepeatedField<\RoadRunner\Metrics\DTO\V1\Objective>
     */
    public function getObjectives()
    {
        return $this->objectives;
    }

    /**
     * Generated from protobuf field <code>repeated .metrics.v1.Objective objectives = 7 [json_name = "objectives"];</code>
     * @param \RoadRunner\Metrics\DTO\V1\Objective[] $var
     * @return $this
     */
    public function setObjectives(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Metrics\DTO\V1\Objective::class);
        $this->objectives = $arr;

        return $this;
    }

}

