<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metrics.v1.DeclareRequest</code>
 */
class DeclareRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.metrics.v1.NamedCollector collector = 1 [json_name = "collector"];</code>
     */
    protected $collector = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Metrics\DTO\V1\NamedCollector $collector
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Metrics\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.NamedCollector collector = 1 [json_name = "collector"];</code>
     * @return \RoadRunner\Metrics\DTO\V1\NamedCollector|null
     */
    public function getCollector()
    {
        return $this->collector;
    }

    public function hasCollector()
    {
        return isset($this->collector);
    }

    public function clearCollector()
    {
        unset($this->collector);
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.NamedCollector collector = 1 [json_name = "collector"];</code>
     * @param \RoadRunner\Metrics\DTO\V1\NamedCollector $var
     * @return $this
     */
    public function setCollector(\RoadRunner\Metrics\DTO\V1\NamedCollector|null $var)
    {
        $this->collector = $var;

        return $this;
    }

}

