<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Spiral\RoadRunner\GRPC;

interface MetricsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "metrics.v1.MetricsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AddRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Add(GRPC\ContextInterface $ctx, AddRequest $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SubRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Sub(GRPC\ContextInterface $ctx, SubRequest $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ObserveRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Observe(GRPC\ContextInterface $ctx, ObserveRequest $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SetRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Set(GRPC\ContextInterface $ctx, SetRequest $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeclareRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Declare(GRPC\ContextInterface $ctx, DeclareRequest $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UnregisterRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Unregister(GRPC\ContextInterface $ctx, UnregisterRequest $in): Response;
}
