<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * NamedCollector wraps a Collector with its registry name; used only by
 * Declare to register a new collector under that name.
 *
 * Generated from protobuf message <code>metrics.v1.NamedCollector</code>
 */
class NamedCollector extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.metrics.v1.Collector collector = 2 [json_name = "collector"];</code>
     */
    protected $collector = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \RoadRunner\Metrics\DTO\V1\Collector $collector
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Metrics\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.Collector collector = 2 [json_name = "collector"];</code>
     * @return \RoadRunner\Metrics\DTO\V1\Collector|null
     */
    public function getCollector()
    {
        return $this->collector;
    }

    public function hasCollector()
    {
        return isset($this->collector);
    }

    public function clearCollector()
    {
        unset($this->collector);
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.Collector collector = 2 [json_name = "collector"];</code>
     * @param \RoadRunner\Metrics\DTO\V1\Collector $var
     * @return $this
     */
    public function setCollector(\RoadRunner\Metrics\DTO\V1\Collector|null $var)
    {
        $this->collector = $var;

        return $this;
    }

}

