<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Objective is a single (quantile, error) pair for Prometheus summary
 * collectors. proto3 forbids float-keyed maps, so summary objectives are
 * modelled as a repeated message rather than `map<double, double>`.
 *
 * Generated from protobuf message <code>metrics.v1.Objective</code>
 */
class Objective extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double quantile = 1 [json_name = "quantile"];</code>
     */
    protected $quantile = 0.0;
    /**
     * Generated from protobuf field <code>double error = 2 [json_name = "error"];</code>
     */
    protected $error = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $quantile
     *     @type float $error
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Metrics\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double quantile = 1 [json_name = "quantile"];</code>
     * @return float
     */
    public function getQuantile()
    {
        return $this->quantile;
    }

    /**
     * Generated from protobuf field <code>double quantile = 1 [json_name = "quantile"];</code>
     * @param float $var
     * @return $this
     */
    public function setQuantile(float $var)
    {
        $this->quantile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double error = 2 [json_name = "error"];</code>
     * @return float
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>double error = 2 [json_name = "error"];</code>
     * @param float $var
     * @return $this
     */
    public function setError(float $var)
    {
        $this->error = $var;

        return $this;
    }

}

