<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics/v1/service.proto

namespace RoadRunner\Metrics\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metrics.v1.ObserveRequest</code>
 */
class ObserveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.metrics.v1.Metric metric = 1 [json_name = "metric"];</code>
     */
    protected $metric = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Metrics\DTO\V1\Metric $metric
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Metrics\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.Metric metric = 1 [json_name = "metric"];</code>
     * @return \RoadRunner\Metrics\DTO\V1\Metric|null
     */
    public function getMetric()
    {
        return $this->metric;
    }

    public function hasMetric()
    {
        return isset($this->metric);
    }

    public function clearMetric()
    {
        unset($this->metric);
    }

    /**
     * Generated from protobuf field <code>.metrics.v1.Metric metric = 1 [json_name = "metric"];</code>
     * @param \RoadRunner\Metrics\DTO\V1\Metric $var
     * @return $this
     */
    public function setMetric(\RoadRunner\Metrics\DTO\V1\Metric|null $var)
    {
        $this->metric = $var;

        return $this;
    }

}

