<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: service/v1/service_rpc.proto

namespace RoadRunner\Service\DTO\V1;

use Spiral\RoadRunner\GRPC;

interface ServiceManagerInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "service.v1.ServiceManager";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Create $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateService(GRPC\ContextInterface $ctx, Create $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Service $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Terminate(GRPC\ContextInterface $ctx, Service $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Service $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Restart(GRPC\ContextInterface $ctx, Service $in): Response;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Service $in
    * @return Status
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetStatus(GRPC\ContextInterface $ctx, Service $in): Status;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Service $in
    * @return Statuses
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetStatuses(GRPC\ContextInterface $ctx, Service $in): Statuses;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Service $in
    * @return List
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListServices(GRPC\ContextInterface $ctx, Service $in): List;
}
