<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: temporal/api/operatorservice/v1/service.proto

namespace Temporal\Api\Operatorservice\V1;

use Spiral\RoadRunner\GRPC;

interface OperatorServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "temporal.api.operatorservice.v1.OperatorService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AddSearchAttributesRequest $in
    * @return AddSearchAttributesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AddSearchAttributes(GRPC\ContextInterface $ctx, AddSearchAttributesRequest $in): AddSearchAttributesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RemoveSearchAttributesRequest $in
    * @return RemoveSearchAttributesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RemoveSearchAttributes(GRPC\ContextInterface $ctx, RemoveSearchAttributesRequest $in): RemoveSearchAttributesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ListSearchAttributesRequest $in
    * @return ListSearchAttributesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListSearchAttributes(GRPC\ContextInterface $ctx, ListSearchAttributesRequest $in): ListSearchAttributesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeleteNamespaceRequest $in
    * @return DeleteNamespaceResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteNamespace(GRPC\ContextInterface $ctx, DeleteNamespaceRequest $in): DeleteNamespaceResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AddOrUpdateRemoteClusterRequest $in
    * @return AddOrUpdateRemoteClusterResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AddOrUpdateRemoteCluster(GRPC\ContextInterface $ctx, AddOrUpdateRemoteClusterRequest $in): AddOrUpdateRemoteClusterResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RemoveRemoteClusterRequest $in
    * @return RemoveRemoteClusterResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RemoveRemoteCluster(GRPC\ContextInterface $ctx, RemoveRemoteClusterRequest $in): RemoveRemoteClusterResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ListClustersRequest $in
    * @return ListClustersResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListClusters(GRPC\ContextInterface $ctx, ListClustersRequest $in): ListClustersResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetNexusEndpointRequest $in
    * @return GetNexusEndpointResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetNexusEndpoint(GRPC\ContextInterface $ctx, GetNexusEndpointRequest $in): GetNexusEndpointResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CreateNexusEndpointRequest $in
    * @return CreateNexusEndpointResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateNexusEndpoint(GRPC\ContextInterface $ctx, CreateNexusEndpointRequest $in): CreateNexusEndpointResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UpdateNexusEndpointRequest $in
    * @return UpdateNexusEndpointResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UpdateNexusEndpoint(GRPC\ContextInterface $ctx, UpdateNexusEndpointRequest $in): UpdateNexusEndpointResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeleteNexusEndpointRequest $in
    * @return DeleteNexusEndpointResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteNexusEndpoint(GRPC\ContextInterface $ctx, DeleteNexusEndpointRequest $in): DeleteNexusEndpointResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ListNexusEndpointsRequest $in
    * @return ListNexusEndpointsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListNexusEndpoints(GRPC\ContextInterface $ctx, ListNexusEndpointsRequest $in): ListNexusEndpointsResponse;
}
