<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v2/response.proto

namespace RoadRunner\Service\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>service.v2.ServiceStatuses</code>
 */
class ServiceStatuses extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .service.v2.ProcessStatus statuses = 1 [json_name = "statuses"];</code>
     */
    private $statuses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Service\DTO\V2\ProcessStatus[] $statuses
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Service\DTO\V2\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .service.v2.ProcessStatus statuses = 1 [json_name = "statuses"];</code>
     * @return RepeatedField<\RoadRunner\Service\DTO\V2\ProcessStatus>
     */
    public function getStatuses()
    {
        return $this->statuses;
    }

    /**
     * Generated from protobuf field <code>repeated .service.v2.ProcessStatus statuses = 1 [json_name = "statuses"];</code>
     * @param \RoadRunner\Service\DTO\V2\ProcessStatus[] $var
     * @return $this
     */
    public function setStatuses(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Service\DTO\V2\ProcessStatus::class);
        $this->statuses = $arr;

        return $this;
    }

}

