<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v2/response.proto

namespace RoadRunner\Service\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>service.v2.ServiceList</code>
 */
class ServiceList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string services = 1 [json_name = "services"];</code>
     */
    private $services;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $services
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Service\DTO\V2\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string services = 1 [json_name = "services"];</code>
     * @return RepeatedField<string>
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * Generated from protobuf field <code>repeated string services = 1 [json_name = "services"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setServices(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->services = $arr;

        return $this;
    }

}

