<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv/v2/kv.proto

namespace RoadRunner\KV\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kv.v2.KvItem</code>
 */
class KvItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration ttl = 3 [json_name = "ttl"];</code>
     */
    protected $ttl = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $value
     *     @type \Google\Protobuf\Duration $ttl
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\KV\DTO\V2\GPBMetadata\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration ttl = 3 [json_name = "ttl"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getTtl()
    {
        return $this->ttl;
    }

    public function hasTtl()
    {
        return isset($this->ttl);
    }

    public function clearTtl()
    {
        unset($this->ttl);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration ttl = 3 [json_name = "ttl"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setTtl(\Google\Protobuf\Duration|null $var)
    {
        $this->ttl = $var;

        return $this;
    }

}

