<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv/v2/response.proto

namespace RoadRunner\KV\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kv.v2.KvResponse</code>
 */
class KvResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .kv.v2.KvItem items = 1 [json_name = "items"];</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\KV\DTO\V2\KvItem[] $items
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\KV\DTO\V2\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .kv.v2.KvItem items = 1 [json_name = "items"];</code>
     * @return RepeatedField<\RoadRunner\KV\DTO\V2\KvItem>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .kv.v2.KvItem items = 1 [json_name = "items"];</code>
     * @param \RoadRunner\KV\DTO\V2\KvItem[] $var
     * @return $this
     */
    public function setItems(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\KV\DTO\V2\KvItem::class);
        $this->items = $arr;

        return $this;
    }

}

