<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/request.proto

namespace RoadRunner\HTTP\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>http.v2.HttpHandlerRequests</code>
 */
class HttpHandlerRequests extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .http.v2.HttpHandlerRequest requests = 1 [json_name = "requests"];</code>
     */
    private $requests;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\HTTP\DTO\V2\HttpHandlerRequest[] $requests
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .http.v2.HttpHandlerRequest requests = 1 [json_name = "requests"];</code>
     * @return RepeatedField<\RoadRunner\HTTP\DTO\V2\HttpHandlerRequest>
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * Generated from protobuf field <code>repeated .http.v2.HttpHandlerRequest requests = 1 [json_name = "requests"];</code>
     * @param \RoadRunner\HTTP\DTO\V2\HttpHandlerRequest[] $var
     * @return $this
     */
    public function setRequests(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V2\HttpHandlerRequest::class);
        $this->requests = $arr;

        return $this;
    }

}

