<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/request.proto

namespace RoadRunner\HTTP\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>http.v2.HttpHandlerFetchRequest</code>
 */
class HttpHandlerFetchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 batch_size = 1 [json_name = "batchSize"];</code>
     */
    protected $batch_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $batch_size
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 batch_size = 1 [json_name = "batchSize"];</code>
     * @return int|string
     */
    public function getBatchSize()
    {
        return $this->batch_size;
    }

    /**
     * Generated from protobuf field <code>int64 batch_size = 1 [json_name = "batchSize"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setBatchSize(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->batch_size = $var;

        return $this;
    }

}

