<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/response.proto

namespace RoadRunner\HTTP\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>http.v2.HttpHandlerResponse</code>
 */
class HttpHandlerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>bytes body = 3 [json_name = "body"];</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>map<string, .http.v2.HttpHeaderValue> headers = 4 [json_name = "headers"];</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int|string $status
     *     @type string $body
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes body = 3 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 3 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v2.HttpHeaderValue> headers = 4 [json_name = "headers"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>map<string, .http.v2.HttpHeaderValue> headers = 4 [json_name = "headers"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\HTTP\DTO\V2\HttpHeaderValue::class);
        $this->headers = $arr;

        return $this;
    }

}

