<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: http/v2/service.proto

namespace RoadRunner\HTTP\DTO\V2;

use Spiral\RoadRunner\GRPC;

interface HttpProxyServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "http.v2.HttpProxyService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Google\Protobuf\GPBEmpty $in
    * @return HttpHandlerRequest
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function FetchRequest(GRPC\ContextInterface $ctx, \Google\Protobuf\GPBEmpty $in): HttpHandlerRequest;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Google\Protobuf\GPBEmpty $in
    * @return HttpHandlerRequest
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function StreamRequest(GRPC\ContextInterface $ctx, \Google\Protobuf\GPBEmpty $in): HttpHandlerRequest;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HttpHandlerFetchRequest $in
    * @return HttpHandlerRequests
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function FetchRequests(GRPC\ContextInterface $ctx, HttpHandlerFetchRequest $in): HttpHandlerRequests;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HttpHandlerResponse $in
    * @return \Google\Protobuf\GPBEmpty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SendResponse(GRPC\ContextInterface $ctx, HttpHandlerResponse $in): \Google\Protobuf\GPBEmpty;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HttpHandlerResponse $in
    * @return \Google\Protobuf\GPBEmpty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function StreamResponse(GRPC\ContextInterface $ctx, HttpHandlerResponse $in): \Google\Protobuf\GPBEmpty;
}
