<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/filter/v1/message.proto

namespace GPBMetadata\Temporal\Api\Filter\V1;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Workflow::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDF\x04\x0A\$temporal/api/filter/v1/message.proto\x12\x16temporal.api.filter.v1\x1A\$temporal/api/enums/v1/workflow.proto\"Q\x0A\x17WorkflowExecutionFilter\x12\x1F\x0A\x0Bworkflow_id\x18\x01 \x01(\x09R\x0AworkflowId\x12\x15\x0A\x06run_id\x18\x02 \x01(\x09R\x05runId\"(\x0A\x12WorkflowTypeFilter\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\"\x8F\x01\x0A\x0FStartTimeFilter\x12?\x0A\x0Dearliest_time\x18\x01 \x01(\x0B2\x1A.google.protobuf.TimestampR\x0CearliestTime\x12;\x0A\x0Blatest_time\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x0AlatestTime\"V\x0A\x0CStatusFilter\x12F\x0A\x06status\x18\x01 \x01(\x0E2..temporal.api.enums.v1.WorkflowExecutionStatusR\x06statusB\x89\x01\x0A\x19io.temporal.api.filter.v1B\x0CMessageProtoP\x01Z#go.temporal.io/api/filter/v1;filter\xAA\x02\x18Temporalio.Api.Filter.V1\xEA\x02\x1BTemporalio::Api::Filter::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

