<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Spiral\RoadRunner\GRPC;

interface CentrifugoApiInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "centrifugal.centrifugo.api.CentrifugoApi";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param BatchRequest $in
    * @return BatchResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Batch(GRPC\ContextInterface $ctx, BatchRequest $in): BatchResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PublishRequest $in
    * @return PublishResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Publish(GRPC\ContextInterface $ctx, PublishRequest $in): PublishResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param BroadcastRequest $in
    * @return BroadcastResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Broadcast(GRPC\ContextInterface $ctx, BroadcastRequest $in): BroadcastResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SubscribeRequest $in
    * @return SubscribeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Subscribe(GRPC\ContextInterface $ctx, SubscribeRequest $in): SubscribeResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UnsubscribeRequest $in
    * @return UnsubscribeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Unsubscribe(GRPC\ContextInterface $ctx, UnsubscribeRequest $in): UnsubscribeResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DisconnectRequest $in
    * @return DisconnectResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Disconnect(GRPC\ContextInterface $ctx, DisconnectRequest $in): DisconnectResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PresenceRequest $in
    * @return PresenceResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Presence(GRPC\ContextInterface $ctx, PresenceRequest $in): PresenceResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PresenceStatsRequest $in
    * @return PresenceStatsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function PresenceStats(GRPC\ContextInterface $ctx, PresenceStatsRequest $in): PresenceStatsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HistoryRequest $in
    * @return HistoryResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function History(GRPC\ContextInterface $ctx, HistoryRequest $in): HistoryResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HistoryRemoveRequest $in
    * @return HistoryRemoveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function HistoryRemove(GRPC\ContextInterface $ctx, HistoryRemoveRequest $in): HistoryRemoveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param InfoRequest $in
    * @return InfoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Info(GRPC\ContextInterface $ctx, InfoRequest $in): InfoResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RPCRequest $in
    * @return RPCResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RPC(GRPC\ContextInterface $ctx, RPCRequest $in): RPCResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RefreshRequest $in
    * @return RefreshResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Refresh(GRPC\ContextInterface $ctx, RefreshRequest $in): RefreshResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ChannelsRequest $in
    * @return ChannelsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Channels(GRPC\ContextInterface $ctx, ChannelsRequest $in): ChannelsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ConnectionsRequest $in
    * @return ConnectionsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Connections(GRPC\ContextInterface $ctx, ConnectionsRequest $in): ConnectionsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UpdateUserStatusRequest $in
    * @return UpdateUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UpdateUserStatus(GRPC\ContextInterface $ctx, UpdateUserStatusRequest $in): UpdateUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetUserStatusRequest $in
    * @return GetUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetUserStatus(GRPC\ContextInterface $ctx, GetUserStatusRequest $in): GetUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeleteUserStatusRequest $in
    * @return DeleteUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteUserStatus(GRPC\ContextInterface $ctx, DeleteUserStatusRequest $in): DeleteUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param BlockUserRequest $in
    * @return BlockUserResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function BlockUser(GRPC\ContextInterface $ctx, BlockUserRequest $in): BlockUserResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UnblockUserRequest $in
    * @return UnblockUserResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UnblockUser(GRPC\ContextInterface $ctx, UnblockUserRequest $in): UnblockUserResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param RevokeTokenRequest $in
    * @return RevokeTokenResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RevokeToken(GRPC\ContextInterface $ctx, RevokeTokenRequest $in): RevokeTokenResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param InvalidateUserTokensRequest $in
    * @return InvalidateUserTokensResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function InvalidateUserTokens(GRPC\ContextInterface $ctx, InvalidateUserTokensRequest $in): InvalidateUserTokensResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceRegisterRequest $in
    * @return DeviceRegisterResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceRegister(GRPC\ContextInterface $ctx, DeviceRegisterRequest $in): DeviceRegisterResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceUpdateRequest $in
    * @return DeviceUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceUpdate(GRPC\ContextInterface $ctx, DeviceUpdateRequest $in): DeviceUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceRemoveRequest $in
    * @return DeviceRemoveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceRemove(GRPC\ContextInterface $ctx, DeviceRemoveRequest $in): DeviceRemoveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceListRequest $in
    * @return DeviceListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceList(GRPC\ContextInterface $ctx, DeviceListRequest $in): DeviceListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceTopicListRequest $in
    * @return DeviceTopicListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceTopicList(GRPC\ContextInterface $ctx, DeviceTopicListRequest $in): DeviceTopicListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param DeviceTopicUpdateRequest $in
    * @return DeviceTopicUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeviceTopicUpdate(GRPC\ContextInterface $ctx, DeviceTopicUpdateRequest $in): DeviceTopicUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserTopicListRequest $in
    * @return UserTopicListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UserTopicList(GRPC\ContextInterface $ctx, UserTopicListRequest $in): UserTopicListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserTopicUpdateRequest $in
    * @return UserTopicUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UserTopicUpdate(GRPC\ContextInterface $ctx, UserTopicUpdateRequest $in): UserTopicUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SendPushNotificationRequest $in
    * @return SendPushNotificationResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SendPushNotification(GRPC\ContextInterface $ctx, SendPushNotificationRequest $in): SendPushNotificationResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UpdatePushStatusRequest $in
    * @return UpdatePushStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UpdatePushStatus(GRPC\ContextInterface $ctx, UpdatePushStatusRequest $in): UpdatePushStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CancelPushRequest $in
    * @return CancelPushResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CancelPush(GRPC\ContextInterface $ctx, CancelPushRequest $in): CancelPushResponse;
}
