<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.DisconnectRequest</code>
 */
class DisconnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Disconnect disconnect = 2 [json_name = "disconnect"];</code>
     */
    protected $disconnect = null;
    /**
     * Generated from protobuf field <code>string client = 3 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>repeated string whitelist = 4 [json_name = "whitelist"];</code>
     */
    private $whitelist;
    /**
     * Generated from protobuf field <code>string session = 5 [json_name = "session"];</code>
     */
    protected $session = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\Disconnect $disconnect
     *     @type string $client
     *     @type string[] $whitelist
     *     @type string $session
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 1 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Disconnect disconnect = 2 [json_name = "disconnect"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\Disconnect|null
     */
    public function getDisconnect()
    {
        return $this->disconnect;
    }

    public function hasDisconnect()
    {
        return isset($this->disconnect);
    }

    public function clearDisconnect()
    {
        unset($this->disconnect);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Disconnect disconnect = 2 [json_name = "disconnect"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\Disconnect $var
     * @return $this
     */
    public function setDisconnect(\RoadRunner\Centrifugal\API\DTO\V1\Disconnect|null $var)
    {
        $this->disconnect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client = 3 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 3 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string whitelist = 4 [json_name = "whitelist"];</code>
     * @return RepeatedField<string>
     */
    public function getWhitelist()
    {
        return $this->whitelist;
    }

    /**
     * Generated from protobuf field <code>repeated string whitelist = 4 [json_name = "whitelist"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setWhitelist(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->whitelist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session = 5 [json_name = "session"];</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>string session = 5 [json_name = "session"];</code>
     * @param string $var
     * @return $this
     */
    public function setSession(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session = $var;

        return $this;
    }

}

