<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.NodeResult</code>
 */
class NodeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uid = 1 [json_name = "uid"];</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string version = 3 [json_name = "version"];</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>uint32 num_clients = 4 [json_name = "numClients"];</code>
     */
    protected $num_clients = 0;
    /**
     * Generated from protobuf field <code>uint32 num_users = 5 [json_name = "numUsers"];</code>
     */
    protected $num_users = 0;
    /**
     * Generated from protobuf field <code>uint32 num_channels = 6 [json_name = "numChannels"];</code>
     */
    protected $num_channels = 0;
    /**
     * Generated from protobuf field <code>uint32 uptime = 7 [json_name = "uptime"];</code>
     */
    protected $uptime = 0;
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Metrics metrics = 8 [json_name = "metrics"];</code>
     */
    protected $metrics = null;
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Process process = 9 [json_name = "process"];</code>
     */
    protected $process = null;
    /**
     * Generated from protobuf field <code>uint32 num_subs = 10 [json_name = "numSubs"];</code>
     */
    protected $num_subs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *     @type string $name
     *     @type string $version
     *     @type int $num_clients
     *     @type int $num_users
     *     @type int $num_channels
     *     @type int $uptime
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\Metrics $metrics
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\Process $process
     *     @type int $num_subs
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uid = 1 [json_name = "uid"];</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 1 [json_name = "uid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 3 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 3 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_clients = 4 [json_name = "numClients"];</code>
     * @return int
     */
    public function getNumClients()
    {
        return $this->num_clients;
    }

    /**
     * Generated from protobuf field <code>uint32 num_clients = 4 [json_name = "numClients"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumClients(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->num_clients = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_users = 5 [json_name = "numUsers"];</code>
     * @return int
     */
    public function getNumUsers()
    {
        return $this->num_users;
    }

    /**
     * Generated from protobuf field <code>uint32 num_users = 5 [json_name = "numUsers"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumUsers(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->num_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_channels = 6 [json_name = "numChannels"];</code>
     * @return int
     */
    public function getNumChannels()
    {
        return $this->num_channels;
    }

    /**
     * Generated from protobuf field <code>uint32 num_channels = 6 [json_name = "numChannels"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumChannels(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->num_channels = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uptime = 7 [json_name = "uptime"];</code>
     * @return int
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>uint32 uptime = 7 [json_name = "uptime"];</code>
     * @param int $var
     * @return $this
     */
    public function setUptime(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Metrics metrics = 8 [json_name = "metrics"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\Metrics|null
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    public function hasMetrics()
    {
        return isset($this->metrics);
    }

    public function clearMetrics()
    {
        unset($this->metrics);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Metrics metrics = 8 [json_name = "metrics"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\Metrics $var
     * @return $this
     */
    public function setMetrics(\RoadRunner\Centrifugal\API\DTO\V1\Metrics|null $var)
    {
        $this->metrics = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Process process = 9 [json_name = "process"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\Process|null
     */
    public function getProcess()
    {
        return $this->process;
    }

    public function hasProcess()
    {
        return isset($this->process);
    }

    public function clearProcess()
    {
        unset($this->process);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Process process = 9 [json_name = "process"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\Process $var
     * @return $this
     */
    public function setProcess(\RoadRunner\Centrifugal\API\DTO\V1\Process|null $var)
    {
        $this->process = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_subs = 10 [json_name = "numSubs"];</code>
     * @return int
     */
    public function getNumSubs()
    {
        return $this->num_subs;
    }

    /**
     * Generated from protobuf field <code>uint32 num_subs = 10 [json_name = "numSubs"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumSubs(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->num_subs = $var;

        return $this;
    }

}

