<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centrifugo/api/v1/api.proto

namespace RoadRunner\Centrifugal\API\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.SubscribeRequest</code>
 */
class SubscribeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string channel = 1 [json_name = "channel"];</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>int64 expire_at = 3 [json_name = "expireAt"];</code>
     */
    protected $expire_at = 0;
    /**
     * Generated from protobuf field <code>bytes info = 4 [json_name = "info"];</code>
     */
    protected $info = '';
    /**
     * Generated from protobuf field <code>string b64info = 5 [json_name = "b64info"];</code>
     */
    protected $b64info = '';
    /**
     * Generated from protobuf field <code>string client = 6 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string b64data = 8 [json_name = "b64data"];</code>
     */
    protected $b64data = '';
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.StreamPosition recover_since = 9 [json_name = "recoverSince"];</code>
     */
    protected $recover_since = null;
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.SubscribeOptionOverride override = 10 [json_name = "override"];</code>
     */
    protected $override = null;
    /**
     * Generated from protobuf field <code>string session = 11 [json_name = "session"];</code>
     */
    protected $session = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $channel
     *     @type string $user
     *     @type int|string $expire_at
     *     @type string $info
     *     @type string $b64info
     *     @type string $client
     *     @type string $data
     *     @type string $b64data
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\StreamPosition $recover_since
     *     @type \RoadRunner\Centrifugal\API\DTO\V1\SubscribeOptionOverride $override
     *     @type string $session
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Centrifugal\API\DTO\V1\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string channel = 1 [json_name = "channel"];</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 1 [json_name = "channel"];</code>
     * @param string $var
     * @return $this
     */
    public function setChannel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 2 [json_name = "user"];</code>
     * @param string $var
     * @return $this
     */
    public function setUser(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 3 [json_name = "expireAt"];</code>
     * @return int|string
     */
    public function getExpireAt()
    {
        return $this->expire_at;
    }

    /**
     * Generated from protobuf field <code>int64 expire_at = 3 [json_name = "expireAt"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes info = 4 [json_name = "info"];</code>
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>bytes info = 4 [json_name = "info"];</code>
     * @param string $var
     * @return $this
     */
    public function setInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64info = 5 [json_name = "b64info"];</code>
     * @return string
     */
    public function getB64Info()
    {
        return $this->b64info;
    }

    /**
     * Generated from protobuf field <code>string b64info = 5 [json_name = "b64info"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Info(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->b64info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client = 6 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 6 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string b64data = 8 [json_name = "b64data"];</code>
     * @return string
     */
    public function getB64Data()
    {
        return $this->b64data;
    }

    /**
     * Generated from protobuf field <code>string b64data = 8 [json_name = "b64data"];</code>
     * @param string $var
     * @return $this
     */
    public function setB64Data(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->b64data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.StreamPosition recover_since = 9 [json_name = "recoverSince"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\StreamPosition|null
     */
    public function getRecoverSince()
    {
        return $this->recover_since;
    }

    public function hasRecoverSince()
    {
        return isset($this->recover_since);
    }

    public function clearRecoverSince()
    {
        unset($this->recover_since);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.StreamPosition recover_since = 9 [json_name = "recoverSince"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\StreamPosition $var
     * @return $this
     */
    public function setRecoverSince(\RoadRunner\Centrifugal\API\DTO\V1\StreamPosition|null $var)
    {
        $this->recover_since = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.SubscribeOptionOverride override = 10 [json_name = "override"];</code>
     * @return \RoadRunner\Centrifugal\API\DTO\V1\SubscribeOptionOverride|null
     */
    public function getOverride()
    {
        return $this->override;
    }

    public function hasOverride()
    {
        return isset($this->override);
    }

    public function clearOverride()
    {
        unset($this->override);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.SubscribeOptionOverride override = 10 [json_name = "override"];</code>
     * @param \RoadRunner\Centrifugal\API\DTO\V1\SubscribeOptionOverride $var
     * @return $this
     */
    public function setOverride(\RoadRunner\Centrifugal\API\DTO\V1\SubscribeOptionOverride|null $var)
    {
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session = 11 [json_name = "session"];</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>string session = 11 [json_name = "session"];</code>
     * @param string $var
     * @return $this
     */
    public function setSession(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session = $var;

        return $this;
    }

}

