<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/sdk/v1/enhanced_stack_trace.proto

namespace GPBMetadata\Temporal\Api\Sdk\V1;

class EnhancedStackTrace
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB1\x07\x0A.temporal/api/sdk/v1/enhanced_stack_trace.proto\x12\x13temporal.api.sdk.v1\"\xBD\x02\x0A\x12EnhancedStackTrace\x128\x0A\x03sdk\x18\x01 \x01(\x0B2&.temporal.api.sdk.v1.StackTraceSDKInfoR\x03sdk\x12N\x0A\x07sources\x18\x02 \x03(\x0B24.temporal.api.sdk.v1.EnhancedStackTrace.SourcesEntryR\x07sources\x127\x0A\x06stacks\x18\x03 \x03(\x0B2\x1F.temporal.api.sdk.v1.StackTraceR\x06stacks\x1Ad\x0A\x0CSourcesEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12>\x0A\x05value\x18\x02 \x01(\x0B2(.temporal.api.sdk.v1.StackTraceFileSliceR\x05value:\x028\x01\"A\x0A\x11StackTraceSDKInfo\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\x12\x18\x0A\x07version\x18\x02 \x01(\x09R\x07version\"P\x0A\x13StackTraceFileSlice\x12\x1F\x0A\x0Bline_offset\x18\x01 \x01(\x0DR\x0AlineOffset\x12\x18\x0A\x07content\x18\x02 \x01(\x09R\x07content\"\xAB\x01\x0A\x16StackTraceFileLocation\x12\x1B\x0A\x09file_path\x18\x01 \x01(\x09R\x08filePath\x12\x12\x0A\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\x0A\x06column\x18\x03 \x01(\x05R\x06column\x12#\x0A\x0Dfunction_name\x18\x04 \x01(\x09R\x0CfunctionName\x12#\x0A\x0Dinternal_code\x18\x05 \x01(\x08R\x0CinternalCode\"W\x0A\x0AStackTrace\x12I\x0A\x09locations\x18\x01 \x03(\x0B2+.temporal.api.sdk.v1.StackTraceFileLocationR\x09locationsB\x85\x01\x0A\x16io.temporal.api.sdk.v1B\x17EnhancedStackTraceProtoP\x01Z\x1Dgo.temporal.io/api/sdk/v1;sdk\xAA\x02\x15Temporalio.Api.Sdk.V1\xEA\x02\x18Temporalio::Api::Sdk::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

