<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/sdk/v1/workflow_metadata.proto

namespace GPBMetadata\Temporal\Api\Sdk\V1;

class WorkflowMetadata
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x80\x06\x0A+temporal/api/sdk/v1/workflow_metadata.proto\x12\x13temporal.api.sdk.v1\"\x84\x01\x0A\x10WorkflowMetadata\x12G\x0A\x0Adefinition\x18\x01 \x01(\x0B2'.temporal.api.sdk.v1.WorkflowDefinitionR\x0Adefinition\x12'\x0A\x0Fcurrent_details\x18\x02 \x01(\x09R\x0EcurrentDetails\"\xCF\x02\x0A\x12WorkflowDefinition\x12\x12\x0A\x04type\x18\x01 \x01(\x09R\x04type\x12_\x0A\x11query_definitions\x18\x02 \x03(\x0B22.temporal.api.sdk.v1.WorkflowInteractionDefinitionR\x10queryDefinitions\x12a\x0A\x12signal_definitions\x18\x03 \x03(\x0B22.temporal.api.sdk.v1.WorkflowInteractionDefinitionR\x11signalDefinitions\x12a\x0A\x12update_definitions\x18\x04 \x03(\x0B22.temporal.api.sdk.v1.WorkflowInteractionDefinitionR\x11updateDefinitions\"U\x0A\x1DWorkflowInteractionDefinition\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\x12 \x0A\x0Bdescription\x18\x02 \x01(\x09R\x0BdescriptionB\x83\x01\x0A\x16io.temporal.api.sdk.v1B\x15WorkflowMetadataProtoP\x01Z\x1Dgo.temporal.io/api/sdk/v1;sdk\xAA\x02\x15Temporalio.Api.Sdk.V1\xEA\x02\x18Temporalio::Api::Sdk::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

