<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: status/v2/service.proto

namespace RoadRunner\Status\DTO\V2;

use Spiral\RoadRunner\GRPC;

interface StatusServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "status.v2.StatusService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param StatusRequest $in
    * @return StatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Status(GRPC\ContextInterface $ctx, StatusRequest $in): StatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param StatusRequest $in
    * @return StatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Ready(GRPC\ContextInterface $ctx, StatusRequest $in): StatusResponse;
}
