<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status/v2/request.proto

namespace RoadRunner\Status\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>status.v2.StatusRequest</code>
 */
class StatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     */
    protected $plugin = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plugin
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Status\DTO\V2\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     * @return string
     */
    public function getPlugin()
    {
        return $this->plugin;
    }

    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlugin(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->plugin = $var;

        return $this;
    }

}

