<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: applogger/v2/applogger.proto

namespace RoadRunner\AppLogger\DTO\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>applogger.v2.LogResponse</code>
 */
class LogResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\AppLogger\DTO\V2\GPBMetadata\Applogger::initOnce();
        parent::__construct($data);
    }

}

