<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/v1/service_rpc.proto

namespace RoadRunner\Service\DTO\V1\GPBMetadata;

class ServiceRpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\Service\DTO\V1\GPBMetadata\Service::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x04\x0A\x1Cservice/v1/service_rpc.proto\x12\x0Aservice.v12\xEF\x02\x0A\x0EServiceManager\x129\x0A\x0DCreateService\x12\x12.service.v1.Create\x1A\x14.service.v1.Response\x126\x0A\x09Terminate\x12\x13.service.v1.Service\x1A\x14.service.v1.Response\x124\x0A\x07Restart\x12\x13.service.v1.Service\x1A\x14.service.v1.Response\x129\x0A\x09GetStatus\x12\x13.service.v1.Service\x1A\x12.service.v1.Status\"\x03\x90\x02\x01\x12=\x0A\x0BGetStatuses\x12\x13.service.v1.Service\x1A\x14.service.v1.Statuses\"\x03\x90\x02\x01\x12:\x0A\x0CListServices\x12\x13.service.v1.Service\x1A\x10.service.v1.List\"\x03\x90\x02\x01B\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v1;serviceV1\xCA\x02\x19RoadRunner\\Service\\DTO\\V1\xE2\x02%RoadRunner\\Service\\DTO\\V1\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

