<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/http.proto

namespace RoadRunner\HTTP\DTO\V2\GPBMetadata;

class Http
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE4\x02\x0A\x12http/v2/http.proto\x12\x07http.v2\"\x9A\x01\x0A\x0AHttpHeader\x127\x0A\x06header\x18\x01 \x03(\x0B2\x1F.http.v2.HttpHeader.HeaderEntryR\x06header\x1AS\x0A\x0BHeaderEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12.\x0A\x05value\x18\x02 \x01(\x0B2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\")\x0A\x0FHttpHeaderValue\x12\x16\x0A\x06values\x18\x01 \x03(\x09R\x06valuesBuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xCA\x02\x16RoadRunner\\HTTP\\DTO\\V2\xE2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

