<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/request.proto

namespace RoadRunner\HTTP\DTO\V2\GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Http::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF0\x07\x0A\x15http/v2/request.proto\x12\x07http.v2\"\xC4\x05\x0A\x12HttpHandlerRequest\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x12\x1F\x0A\x0Bremote_addr\x18\x02 \x01(\x09R\x0AremoteAddr\x12\x1A\x0A\x08protocol\x18\x03 \x01(\x09R\x08protocol\x12\x16\x0A\x06method\x18\x04 \x01(\x09R\x06method\x12\x10\x0A\x03uri\x18\x05 \x01(\x09R\x03uri\x12?\x0A\x06header\x18\x06 \x03(\x0B2'.http.v2.HttpHandlerRequest.HeaderEntryR\x06header\x12B\x0A\x07cookies\x18\x07 \x03(\x0B2(.http.v2.HttpHandlerRequest.CookiesEntryR\x07cookies\x12\x1B\x0A\x09raw_query\x18\x08 \x01(\x09R\x08rawQuery\x12\x16\x0A\x06parsed\x18\x09 \x01(\x08R\x06parsed\x12\x18\x0A\x07uploads\x18\x0A \x01(\x0CR\x07uploads\x12K\x0A\x0Aattributes\x18\x0B \x03(\x0B2+.http.v2.HttpHandlerRequest.AttributesEntryR\x0Aattributes\x12\x12\x0A\x04body\x18\x0C \x01(\x0CR\x04body\x1AS\x0A\x0BHeaderEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12.\x0A\x05value\x18\x02 \x01(\x0B2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\x1AT\x0A\x0CCookiesEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12.\x0A\x05value\x18\x02 \x01(\x0B2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\x1AW\x0A\x0FAttributesEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12.\x0A\x05value\x18\x02 \x01(\x0B2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\"8\x0A\x17HttpHandlerFetchRequest\x12\x1D\x0A\x0Abatch_size\x18\x01 \x01(\x03R\x09batchSize\"N\x0A\x13HttpHandlerRequests\x127\x0A\x08requests\x18\x01 \x03(\x0B2\x1B.http.v2.HttpHandlerRequestR\x08requestsBuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xCA\x02\x16RoadRunner\\HTTP\\DTO\\V2\xE2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

