<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/response.proto

namespace RoadRunner\HTTP\DTO\V2\GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Http::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8F\x03\x0A\x16http/v2/response.proto\x12\x07http.v2\"\xEC\x01\x0A\x13HttpHandlerResponse\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x12\x16\x0A\x06status\x18\x02 \x01(\x03R\x06status\x12\x12\x0A\x04body\x18\x03 \x01(\x0CR\x04body\x12C\x0A\x07headers\x18\x04 \x03(\x0B2).http.v2.HttpHandlerResponse.HeadersEntryR\x07headers\x1AT\x0A\x0CHeadersEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12.\x0A\x05value\x18\x02 \x01(\x0B2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01BuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xCA\x02\x16RoadRunner\\HTTP\\DTO\\V2\xE2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

