<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http/v2/service.proto

namespace RoadRunner\HTTP\DTO\V2\GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Request::initOnce();
        \RoadRunner\HTTP\DTO\V2\GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD1\x04\x0A\x15http/v2/service.proto\x12\x07http.v2\x1A\x15http/v2/request.proto\x1A\x16http/v2/response.proto2\x80\x03\x0A\x10HttpProxyService\x12C\x0A\x0CFetchRequest\x12\x16.google.protobuf.Empty\x1A\x1B.http.v2.HttpHandlerRequest\x12F\x0A\x0DStreamRequest\x12\x16.google.protobuf.Empty\x1A\x1B.http.v2.HttpHandlerRequest0\x01\x12O\x0A\x0DFetchRequests\x12 .http.v2.HttpHandlerFetchRequest\x1A\x1C.http.v2.HttpHandlerRequests\x12D\x0A\x0CSendResponse\x12\x1C.http.v2.HttpHandlerResponse\x1A\x16.google.protobuf.Empty\x12H\x0A\x0EStreamResponse\x12\x1C.http.v2.HttpHandlerResponse\x1A\x16.google.protobuf.Empty(\x01BuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xCA\x02\x16RoadRunner\\HTTP\\DTO\\V2\xE2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

