<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/replication/v1/message.proto

namespace GPBMetadata\Temporal\Api\Replication\V1;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\PBNamespace::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBA\x05\x0A)temporal/api/replication/v1/message.proto\x12\x1Btemporal.api.replication.v1\x1A%temporal/api/enums/v1/namespace.proto\"=\x0A\x18ClusterReplicationConfig\x12!\x0A\x0Ccluster_name\x18\x01 \x01(\x09R\x0BclusterName\"\xDE\x01\x0A\x1ANamespaceReplicationConfig\x12.\x0A\x13active_cluster_name\x18\x01 \x01(\x09R\x11activeClusterName\x12Q\x0A\x08clusters\x18\x02 \x03(\x0B25.temporal.api.replication.v1.ClusterReplicationConfigR\x08clusters\x12=\x0A\x05state\x18\x03 \x01(\x0E2'.temporal.api.enums.v1.ReplicationStateR\x05state\"|\x0A\x0EFailoverStatus\x12?\x0A\x0Dfailover_time\x18\x01 \x01(\x0B2\x1A.google.protobuf.TimestampR\x0CfailoverTime\x12)\x0A\x10failover_version\x18\x02 \x01(\x03R\x0FfailoverVersionB\xA2\x01\x0A\x1Eio.temporal.api.replication.v1B\x0CMessageProtoP\x01Z-go.temporal.io/api/replication/v1;replication\xAA\x02\x1DTemporalio.Api.Replication.V1\xEA\x02 Temporalio::Api::Replication::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

