<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resetter/v1/service.proto

namespace RoadRunner\Resetter\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resetter.v1.ListPluginsRequest</code>
 */
class ListPluginsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Resetter\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

}

