<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resetter/v1/service.proto

namespace RoadRunner\Resetter\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resetter.v1.ResetRequest</code>
 */
class ResetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     */
    protected $plugin = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plugin
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Resetter\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     * @return string
     */
    public function getPlugin()
    {
        return $this->plugin;
    }

    /**
     * Generated from protobuf field <code>string plugin = 1 [json_name = "plugin"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlugin(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->plugin = $var;

        return $this;
    }

}

