<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: resetter/v1/service.proto

namespace RoadRunner\Resetter\DTO\V1;

use Spiral\RoadRunner\GRPC;

interface ResetterServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "resetter.v1.ResetterService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ListPluginsRequest $in
    * @return PluginsList
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListPlugins(GRPC\ContextInterface $ctx, ListPluginsRequest $in): PluginsList;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ResetRequest $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Reset(GRPC\ContextInterface $ctx, ResetRequest $in): Response;
}
