<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: informer/v1/service.proto

namespace RoadRunner\Informer\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>informer.v1.JobsList</code>
 */
class JobsList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .informer.v1.JobState states = 1 [json_name = "states"];</code>
     */
    private $states;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Informer\DTO\V1\JobState[] $states
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Informer\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .informer.v1.JobState states = 1 [json_name = "states"];</code>
     * @return RepeatedField<\RoadRunner\Informer\DTO\V1\JobState>
     */
    public function getStates()
    {
        return $this->states;
    }

    /**
     * Generated from protobuf field <code>repeated .informer.v1.JobState states = 1 [json_name = "states"];</code>
     * @param \RoadRunner\Informer\DTO\V1\JobState[] $var
     * @return $this
     */
    public function setStates(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Informer\DTO\V1\JobState::class);
        $this->states = $arr;

        return $this;
    }

}

