<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: informer/v1/service.proto

namespace RoadRunner\Informer\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ProcessState mirrors github.com/roadrunner-server/pool/v2/state/process.State —
 * one entry per OS-level worker process managed by a plugin. Field widths match
 * the existing service.v1.Status convention (int32 pid, float cpu_percent)
 * rather than the Go-source int64/float64; PIDs fit in int32 per POSIX, and a
 * percentage value comfortably fits in float32.
 *
 * Generated from protobuf message <code>informer.v1.ProcessState</code>
 */
class ProcessState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 pid = 1 [json_name = "pid"];</code>
     */
    protected $pid = 0;
    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint64 num_execs = 3 [json_name = "numExecs"];</code>
     */
    protected $num_execs = 0;
    /**
     * Generated from protobuf field <code>int64 created = 4 [json_name = "created"];</code>
     */
    protected $created = 0;
    /**
     * Generated from protobuf field <code>uint64 memory_usage = 5 [json_name = "memoryUsage"];</code>
     */
    protected $memory_usage = 0;
    /**
     * Generated from protobuf field <code>float cpu_percent = 6 [json_name = "cpuPercent"];</code>
     */
    protected $cpu_percent = 0.0;
    /**
     * Generated from protobuf field <code>string command = 7 [json_name = "command"];</code>
     */
    protected $command = '';
    /**
     * Generated from protobuf field <code>string status_str = 8 [json_name = "statusStr"];</code>
     */
    protected $status_str = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pid
     *     @type int|string $status
     *     @type int|string $num_execs
     *     @type int|string $created
     *     @type int|string $memory_usage
     *     @type float $cpu_percent
     *     @type string $command
     *     @type string $status_str
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Informer\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 pid = 1 [json_name = "pid"];</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>int32 pid = 1 [json_name = "pid"];</code>
     * @param int $var
     * @return $this
     */
    public function setPid(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 2 [json_name = "status"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 num_execs = 3 [json_name = "numExecs"];</code>
     * @return int|string
     */
    public function getNumExecs()
    {
        return $this->num_execs;
    }

    /**
     * Generated from protobuf field <code>uint64 num_execs = 3 [json_name = "numExecs"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumExecs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->num_execs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created = 4 [json_name = "created"];</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Generated from protobuf field <code>int64 created = 4 [json_name = "created"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 memory_usage = 5 [json_name = "memoryUsage"];</code>
     * @return int|string
     */
    public function getMemoryUsage()
    {
        return $this->memory_usage;
    }

    /**
     * Generated from protobuf field <code>uint64 memory_usage = 5 [json_name = "memoryUsage"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemoryUsage(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->memory_usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float cpu_percent = 6 [json_name = "cpuPercent"];</code>
     * @return float
     */
    public function getCpuPercent()
    {
        return $this->cpu_percent;
    }

    /**
     * Generated from protobuf field <code>float cpu_percent = 6 [json_name = "cpuPercent"];</code>
     * @param float $var
     * @return $this
     */
    public function setCpuPercent(float $var)
    {
        $this->cpu_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string command = 7 [json_name = "command"];</code>
     * @return string
     */
    public function getCommand()
    {
        return $this->command;
    }

    /**
     * Generated from protobuf field <code>string command = 7 [json_name = "command"];</code>
     * @param string $var
     * @return $this
     */
    public function setCommand(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->command = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status_str = 8 [json_name = "statusStr"];</code>
     * @return string
     */
    public function getStatusStr()
    {
        return $this->status_str;
    }

    /**
     * Generated from protobuf field <code>string status_str = 8 [json_name = "statusStr"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatusStr(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status_str = $var;

        return $this;
    }

}

