<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: informer/v1/service.proto

namespace RoadRunner\Informer\DTO\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>informer.v1.WorkersList</code>
 */
class WorkersList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .informer.v1.ProcessState workers = 1 [json_name = "workers"];</code>
     */
    private $workers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RoadRunner\Informer\DTO\V1\ProcessState[] $workers
     * }
     */
    public function __construct($data = NULL) {
        \RoadRunner\Informer\DTO\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .informer.v1.ProcessState workers = 1 [json_name = "workers"];</code>
     * @return RepeatedField<\RoadRunner\Informer\DTO\V1\ProcessState>
     */
    public function getWorkers()
    {
        return $this->workers;
    }

    /**
     * Generated from protobuf field <code>repeated .informer.v1.ProcessState workers = 1 [json_name = "workers"];</code>
     * @param \RoadRunner\Informer\DTO\V1\ProcessState[] $var
     * @return $this
     */
    public function setWorkers(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RoadRunner\Informer\DTO\V1\ProcessState::class);
        $this->workers = $arr;

        return $this;
    }

}

