<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websockets/v1/websockets.proto

namespace RoadRunner\Websockets\DTO\V1\GPBMetadata;

class Websockets
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF9\x02\x0A\x1Ewebsockets/v1/websockets.proto\x12\x0Dwebsockets.v1\"U\x0A\x07Message\x12\x18\x0A\x07command\x18\x01 \x01(\x09R\x07command\x12\x16\x0A\x06topics\x18\x02 \x03(\x09R\x06topics\x12\x18\x0A\x07payload\x18\x03 \x01(\x0CR\x07payload\"=\x0A\x07Request\x122\x0A\x08messages\x18\x01 \x03(\x0B2\x16.websockets.v1.MessageR\x08messages\"\x1A\x0A\x08Response\x12\x0E\x0A\x02ok\x18\x01 \x01(\x08R\x02okB\x8D\x01ZAgithub.com/roadrunner-server/api-go/v6/websockets/v1;websocketsV1\xCA\x02\x1CRoadRunner\\Websockets\\DTO\\V1\xE2\x02(RoadRunner\\Websockets\\DTO\\V1\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

